### PR TITLE
Version bump to 0.11.2

### PR DESCRIPTION
**Pull request by israel-hdez**
Preparation to release version v0.11.2

### CODE REVIEW

**Comment by andyi2it** [comment]
@israel-hdez Can you cherry pick this commit as part of your pr. This change includes other poetry lock file changes that are missing.
https://github.com/andyi2it/kserve/commit/a2ab9c4ef572c6d4e359af4726fbe73097cfef83

**Comment by israel-hdez** [comment]
@andyi2it Done.

I think it would be good if release [instructions can be updated](https://github.com/kserve/kserve/blob/master/release/RELEASE_PROCESS_v2.md#on-the-release-day) to reflect what you did.

**Comment by andyi2it** [comment]
> @andyi2it Done.
> 
> I think it would be good if release [instructions can be updated](https://github.com/kserve/kserve/blob/master/release/RELEASE_PROCESS_v2.md#on-the-release-day) to reflect what you did.

Yes, there is a new PR that I am working on that will add this information.

**Review by andyi2it — APPROVED** [review]

**Pull request merged**
