### PR TITLE
use enum value in request validation

### PR DESCRIPTION
**Pull request by luranhe**
**What this PR does / why we need it**:
Other method such as `.predict` assume that the enum value is used for the protocol, but the validation checks against the actual enum instead.

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] New unit test to check model validation 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by luranhe** [comment]
/assign @jinchihe

May I ask where the unit tests for this are?

**Comment by yuzisun** [comment]
> /assign @jinchihe
> 
> May I ask where the unit tests for this are?

@luranhe good catch! the tests are [here](https://github.com/kserve/kserve/blob/master/python/kserve/test/test_server.py), please help add the validation tests, thanks!!

please follow https://github.com/kserve/kserve/pull/2249/checks?check_run_id=6907004387 to assign the commit.

**Comment by luranhe** [comment]
May I ask what the failing test is? Is it related to my PR?

**Comment by yuzisun** [comment]
> May I ask what the failing test is? Is it related to my PR?

@luranhe can you help rebase from master, it was an issue when migrating e2e tests to GitHub action, should be fixed now.

**Comment by luranhe** [comment]
Got it, thank you so much @yuzisun

**Comment by yuzisun** [comment]
Thanks @luranhe !! Awesome work for your first contribution!

/lgtm
/approve

**Pull request merged**
