### PR TITLE
dep ensure to sync up code.

### PR DESCRIPTION
**Pull request by gyliu513**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfserving/28)

### CODE REVIEW

**Comment by ellis-bigelow** [comment]
Hi Guang,
I can't accept a PR like this until we have e2e testing. It's great that you're trying to contribute though. Ping up in kubeflow slack and we can coordinate some feature work if you're interested.

**Comment by gyliu513** [comment]
@ellis-bigelow thanks, but I think we should always run `dep ensure` to make sure we are always using right vendors, this can also help the daily development as well.

I found kubeflow do not have a channel named as kfserving, are you planning to create one? ;-)

**Comment by gaocegege** [comment]
@gyliu513 https://kubeflow.slack.com/messages/CH6E58LNP/

**Comment by cliveseldon** [comment]
Can we clarify if we should do `dep ensure` and commit updates. With the current `master` code doing `dep ensure` adds files to vendor so I assume these have not been committed in previous PRs? I'm newish to Go so want to check best practice, especially as we are still using `dep` as kubebuilder can't use modules yet.

**Comment by gyliu513** [comment]
@cliveseldon I'd prefer that we always keep the vendor up-to-date based on `Gopkg.toml`. But let us wait more comments from @ellis-bigelow

**Comment by yuzisun** [comment]
> Can we clarify if we should do `dep ensure` and commit updates. With the current `master` code doing `dep ensure` adds files to vendor so I assume these have not been committed in previous PRs? I'm newish to Go so want to check best practice, especially as we are still using `dep` as kubebuilder can't use modules yet.

ye that's best practice as it gives you reproducible builds and you do not necessarily run `dep ensure` after checking out the repo , see the reference here.
https://github.com/golang/dep/blob/master/docs/FAQ.md#best-practices-1. I am not exactly sure how those files got missed, possibly upstream change or my fault :( but I assume I checked in everything after `dep ensure`.

**Comment by yuzisun** [comment]
@gyliu513 I think Ellis's concern is that we have not setup e2e tests yet to verify this, I am working on that right now as a priority.

**Pull request closed without merging**
