### PR TITLE
Fix Kubernetes Doc Links 

### PR DESCRIPTION
**Pull request by jyono**
**What this PR does / why we need it**:
Existing docs return a 404. They are simply invalid.. 

**Type of changes**
Please delete options that are not relevant.

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Review by spolti — APPROVED** [review]
/lgtm

**Review by terrytangyuan — COMMENTED** [review]
Could you sign the DCO for your commits?

**Comment by jyono** [comment]
> Could you sign the DCO for your commits?

@terrytangyuan  okay, finally got it right :sweat_smile: :

**Comment by spolti** [comment]
guess you need to rebase

**Comment by jyono** [comment]
> guess you need to rebase

synced the fork. good now :grin:.

**Comment by jyono** [comment]
> guess you need to rebase

@spolti 
synced the fork. good now :grin:.

**Review by spolti — APPROVED** [review]
Thanks

/lgtm

**Comment by yuzisun** [comment]
@jyono seems like the codegen is still out of sync

**Comment by jyono** [comment]
> @jyono seems like the codegen is still out of sync

Do you have any advice on fixing it? the error log is gone. I've been trying 

`make generate` and `KSERVE_PATH="github.com/kserve/kserve" make generate` locally, but am getting errors 

```
ERROR:
	 API rule check failed. Reported violations in file hack/current_violation_exceptions.list differ from known violations in file hack/violation_exceptions.list.

make: *** [Makefile:190: generate] Error 1
```

I was on vacation for a week so it seems the GHA logs are gone. 

Maybe another approval to run codegen again? 

/assign @njhill

**Comment by jyono** [comment]
i've still had no luck. any links or pointers to get the generation working?

**Review by yuzisun — APPROVED** [review]
/lgtm
/approve

**Review by terrytangyuan — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by jyono** [comment]
@terrytangyuan thank you!!! :pray:

**Pull request merged**
