### PR TITLE
update protobuf version

### PR DESCRIPTION
**Pull request by lre**
**What this PR does / why we need it**:
This is to get to the new version of protobuf with significantly better parsing performance than previous releases, especially for large payloads

https://protobuf.dev/news/2022-05-06/

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] paddlepaddle still depends on the old prtobuf version 

**Release note**:

```release-note
Bump protobuf version to ^4.25.0
```

### CODE REVIEW

**Comment by yuzisun** [comment]
@lre Thanks for the PR! can you help create an issue and link the PR?

**Review by terrytangyuan — COMMENTED** [review]
CI builds seem to be failing. Could you take a look?

**Comment by AndersBennedsgaard** [comment]
Not to be annoying, but @lre could you take another look? I'm trying to use KServe together with Kubeflow pipelines, which depends on Protobuf v4, which makes it very annoying to integrate the two until this has been merged

**Comment by papagala** [comment]
This MR would be incredible to merge as we cannot install `kserve` with latest version of KFP in the same package. Are there any plans to revive this MR? Thanks for the hard work everybody

**Comment by lre** [comment]
I dont have the time to follow trough on this PR right now. Will close it but feel free to take it over. Thanks

**Pull request closed without merging**
