### PR TITLE
update fastapi>=0.108.0 && unicorn>=0.21.1

### PR DESCRIPTION
**Pull request by gujingit**
**What this PR does / why we need it**:
update fastapi>=0.108.0 && unicorn>=0.21.1

**Type of changes**
Please delete options that are not relevant.

- [ ] Dep update (non-breaking change which adds functionality)

**Release note**:

```release-note
update fastapi>=0.108.0 && unicorn>=0.21.1
```

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
What is the motivation for this change? Is there any issue you are trying to fix?

**Comment by yuzisun** [comment]
> What is the motivation for this change? Is there any issue you are trying to fix?

@terrytangyuan I have talked to them they are from alicloud and @gujingit has linked the issue [here](https://github.com/alibaba/rtp-llm/pull/20).  Though there is [another PR](https://github.com/kserve/kserve/pull/3374) also upgrading fastapi version.

**Comment by terrytangyuan** [comment]
Sounds good. It would be great if you can update PR description

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by yuzisun** [comment]
Thanks @gujingit ! we have upgraded the dependency in https://github.com/kserve/kserve/pull/3374, so closing yours.

**Pull request closed without merging**
