### PR TITLE
Update ray to 1.9.2

### PR DESCRIPTION
**Pull request by markwinter**
**What this PR does / why we need it**:

Updates ray to 1.9.2 https://github.com/ray-project/ray/releases/tag/ray-1.9.2
It only bumps log4j version, no changes to core etc.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Review by jerrygb — APPROVED** [review]
LGTM

**Comment by yuzisun** [comment]
@markwinter seems your branch is behind for quite a few commits, can you help rebase from the master? there was a fix for the storage uri with lightgbm e2e tests

**Pull request merged**
