### PR TITLE
Increase timeout to make unit test stable

### PR DESCRIPTION
**Pull request by Jooho**
**What this PR does / why we need it**:

kserve agent watcher unit test is not stable and it fails a lot locally. I am not sure it is related to my system but it always fails with the following errors:
~~~
2024/07/18 07:03:18 Deleted temp dir /tmp/example3994517843

------------------------------
• [FAILED] [1.001 seconds]
Watcher Use HTTP(S) Downloader Getting new model events [It] should download and load the new models
/home/kserve/pkg/agent/watcher_test.go:679

  [FAILED] Timed out after 1.000s.
  Expected
      <int>: 0
  to equal
      <int>: 1
  In [It] at: /home/kserve/pkg/agent/watcher_test.go:739 @ 07/18/24 07:03:18.357
~~~

After increasing the timeout to 2 minutes, it always succeeds. This is just a timeout increase, so if a unit test passes faster than the timeout, it will take the same amount of time as before.

slack discussion: https://cloud-native.slack.com/archives/C06AH2C3K8B/p1721286710777179

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.
no code changes. so it does not need to be tested.
```
make test
```
**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Review by sivanantha321 — APPROVED** [review]

**Comment by Jooho** [comment]
@yuzisun if you have time, please review this. it is not code change. just increase the timeout for the test.

**Pull request merged**
