### PR TITLE
Storage Initializer support single digit azure DNS zone ID

### LINKED ISSUE #4069: Azure storage download single digit DNS zone ID not supported
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Using an azure blob URI with single digit zone ID (eg. `https://test.z1.blob.storage.azure.net"`) will not be matched to download azure blob (similar for azure file share). 
Azure [documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview#azure-dns-zone-endpoints-preview) mentions the schema ranges from `z00` to `z55`. However, provider in our environment has single digit DNS zone IDs.

**What did you expect to happen:**
Storage initializer should match and download if Azure DNS zone ID is single digit.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by bentohset**
**What this PR does / why we need it**:
- allows regex matching for single digit DNS zone ID as well

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4069 

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by bentohset** [comment]
cc @lizzzcai

**Comment by lizzzcai** [comment]
Thanks. can you help to add one example to the [test](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage/test/test_storage.py#L265) as well.

**Pull request merged**
