### PR TITLE
Allow rerunning failed workflows by comment

### PR DESCRIPTION
**Pull request by andyi2it**
**What this PR does / why we need it**:

### Re-running failed tests
The following commands are supported by this action:

`/rerun-all` - rerun all failed workflows.
`/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### Some notes:

The PR either must have an `ok-to-test` label present on the PR, or the user who writes a command must be an organization member, or repo owner, contributor, or collaborator.
Typically `ok-to-test` can/should only be applied by repo reviewers/approvers to prevent spam and abuse.

**Reference:** https://github.com/estroz/rerun-actions 

**Fixes** #3631 

**Type of changes**
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

```release-note
NONE
```

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
This is cool. Can you test it in a fork and see if it works?

**Comment by terrytangyuan** [comment]
Kubeflow uses `/retest` from prowbot. Perhaps we can enable that instead of adding a new workflow?

**Comment by spolti** [comment]
This is very nice, will add it in the PR template so everyone can see that it is possible :)

**Pull request merged**
