### PR TITLE
Fix path to kserve.yaml in quick_install.sh script

### PR DESCRIPTION
**Pull request by iamahern**
**What this PR does / why we need it**:
The current quick install script is broken. It will install Istio, KNative, and Cert Manager, but the KServe install itself will fix.

The script is attempting to install KServe from a local filesystem location (`install/${KSERVE_VERSION}/${KSERVE_CONFIG}`). This path does not exist. It appears to want to refer to the release GH release file (`https://github.com/kserve/kserve/releases/download/${KSERVE_VERSION}/${KSERVE_CONFIG}`).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

I could not find an existing issue.

**Special notes for your reviewer**:

To validate/reproduce:

1. Create a new  / empty Kind / Minikube install (on MacOS 4GB / 4CPU seems to do the trick).
2. `cd` into an empty directory.
3. (To reproduce) Run the quick install instructions: https://kserve.github.io/website/get_started/#install-the-kserve-quickstart-environment
4. (To validate) Run the patched script in the PR.

ALSO - the existing quick start needs to be patched to get new users up and running once the fix is confirmed.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuzisun** [comment]
@iamahern Did you install from the KServe root directory?

**Comment by iamahern** [comment]
@yuzisun - No. I followed the instructions on the KServe website here:
https://kserve.github.io/website/get_started/

Based on the instructions, I should not need to download/run from the root of the code repo.

**Comment by yuzisun** [comment]
> @yuzisun - No. I followed the instructions on the KServe website here: https://kserve.github.io/website/get_started/
> 
> Based on the instructions, I should not need to download/run from the root of the code repo.

Ah make sense! Thanks for the fix!

**Pull request merged**
