### PR TITLE
Update ModelMesh version to v0.11.0-rc0

### PR DESCRIPTION
**Pull request by rafvasq**
**What this PR does / why we need it**:
Updates ModelMesh in preparation for the upcoming v0.11 release

**Type of changes**

- [x] This change requires a documentation update

### CODE REVIEW

**Comment by ckadner** [comment]
@Jooho -- could you help syncing the WebHook and HPA changes from ModelMesh PR [modelmesh-serving#342](https://github.com/kserve/modelmesh-serving/pull/342)?

The corresponding helm charts should be under [charts/kserve-resources/templates/modelmesh](https://github.com/kserve/kserve/tree/master/charts/kserve-resources/templates/modelmesh). There are quite a few discrepancies between the [ModelMesh Helm charts in `kserve`](https://github.com/kserve/kserve/tree/master/charts/kserve-resources/templates/modelmesh) and the [Kustomize manifests in ModelMesh](https://github.com/kserve/modelmesh-serving/tree/main/config)

Thank you!!! 🙏

**Comment by yuzisun** [comment]
Thanks @ckadner !

/lgtm
/approve

**Comment by ckadner** [comment]
Thanks @yuzisun -- should I create another PR to update the [`release-0.11`](https://github.com/kserve/kserve/commits/release-0.11) branch or will you cherry pick from this one?

**Comment by yuzisun** [comment]
> Thanks @yuzisun -- should I create another PR to update the [`release-0.11`](https://github.com/kserve/kserve/commits/release-0.11) branch or will you cherry pick from this one?

We will do another RC release based off master and then start cherry picking if needed.

**Pull request merged**
