### PR TITLE
Fix in several CVEs ART explainer image

### PR DESCRIPTION
**Pull request by andresmascl**
Signed-off-by: andresmascl <andresma@gmail.com>

**What this PR does / why we need it**:
Fixing critical CVEs in latest `art-explainer` version of `kserve/art-explainer` image
Comparing this to latest stable kserve/art-explainer image:
grype-old-img
grype-new-img

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Not sure there's an open issue for this

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.

`Ran test_v1beta1_art_explainer_spec.py` test
test-new-img

- Logs

**Special notes for your reviewer**:

This PR only changes image versions

**Release note**:

```release-note
Fix several critical vulnerabilities (CVEs) in kserve/art-explainer
```

### CODE REVIEW

**Comment by yuzisun** [comment]
@andresmascl can you help rebase from the master?

**Comment by andresmascl** [comment]
@yuzisun All done 👍

**Comment by yuzisun** [comment]
@andresmascl We have changed the python dependency management quite a bit recently, please help create a new PR if this is still an issue.

**Pull request closed without merging**
