### PR TITLE
Enable Server-Side Apply for Kustomize Overlays in Test Environment

### PR DESCRIPTION
**Pull request by Jooho**
**What this PR does / why we need it**:
With [this PR](https://github.com/kserve/kserve/pull/3871), the inference service CRD size will be increased from 672k to 757k 
~~~
ls -alh /tmp/isvc_old.yaml 
-rw-r--r-- 1 jooho jooho 672K Aug 20 07:08 /tmp/isvc_old.yaml 

ls -alh /tmp/isvc_new.yaml 
-rw-r--r-- 1 jooho jooho 757K Aug 20 07:05 /tmp/isvc_new.yaml 
~~~
e2e test ci failed to create  the new CRD with the following error msg:
~~~
The CustomResourceDefinition "inferenceservices.serving.kserve.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes 
~~~

When `kubectl apply` used, the whole specification is added to the annotation `last-applied-configuration`

This PR addresses an issue encountered during the e2e tests, which is related to the problem described in [kserve/kserve#3487](https://github.com/kserve/kserve/issues/3487). The changes aim to prevent similar issues from affecting future test runs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
kserve crd needs to be installed with server side apply
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by sivanantha321** [comment]
@Jooho We also have to update in other make targets like `deploy` `deploy-dev` otherwise those won't work anymore once the PR is merged.

**Comment by sivanantha321** [comment]
We have to stick to either server side apply or client side apply throughout all the places. They don't work well with each other. It may lead to confusing errors.

**Comment by spolti** [comment]
And a side node in the README or docs about it to instruct users who might get this issue when deploying the operator manually would be helpful as well.

**Review by terrytangyuan — COMMENTED** [review]
Another temporary solution is to use the minimal CRD yaml for e2e for CI. https://github.com/kserve/kserve/tree/master/charts/kserve-crd-minimal/templates

**Comment by Jooho** [comment]
> We have to stick to either server-side apply or client-side apply throughout all the places. They don't work well with each other. It may lead to confusing errors.

I agreed but it should be a KServe-related manifest(isvc, sr and so on) only. For the others such as minio, istio, knaitve and so on it does not need to use server-side. I updated PR

**Comment by Jooho** [comment]
> And a side node in the README or docs about it to instruct users who might get this issue when deploying the operator manually would be helpful as well.

Yes, I like this idea. While I worked on the new API PR, I hit some weird issues and I realized it could be solved if I knew the way. So I am thinking of creating a new doc `COMMON_ISSUES_AND_SOLUTIONS.md` explaining typical issues and solutions with another PR.

**Comment by Jooho** [comment]
@spolti https://github.com/kserve/kserve/pull/3878

**Comment by Jooho** [comment]
@yuzisun Could you please review this pr?

**Comment by yuzisun** [comment]
> @yuzisun Could you please review this pr?

I'd really like to get rid of this last applied annotation, it is only a problem for applied kustomized yaml and this isn't an issue for helm chart installation.

**Comment by yuzisun** [comment]
@Jooho The website installation needs to be updated to reflect this change
https://kserve.github.io/website/latest/admin/serverless/serverless/#5-install-kserve-built-in-clusterservingruntimes

**Comment by yuzisun** [comment]
> @Jooho The website installation needs to be updated to reflect this change https://kserve.github.io/website/latest/admin/serverless/serverless/#5-install-kserve-built-in-clusterservingruntimes

created https://github.com/kserve/website/issues/392

**Review by yuzisun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
