### PR TITLE
[bugfix]: support kubectl server version correctly

### PR DESCRIPTION
**Pull request by anencore94**
**What this PR does / why we need it**:
Parse kubernetes server version `KUBE_VERSION` in general.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
The current parsing check the length of the character, but it may parse wrong version sometimes.
For my case, my kubectl was built on my own from git repo(kubernetes).
So the result of `kubectl version --short=true` was as following:
```
Client Version: v1.23.0-alpha.3.605+9bcfa71e3121ec-dirty
Server Version: v1.24.1
```

Since the previsious parsing depends on the number of characters, `KUBE_VERSION` became `e3`.
So I couldn't use `quick_install.sh` now.

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by andyi2it** [comment]
@anencore94 
Thanks for the contribution.
Would this be a better solution?
```shell
kubectl version --short=true | awk 'FNR == 2 {print}'| awk -F '.' '{print $2}'
```

This would only use `awk`.

Also, please sign your commit by doing `git commit -s --amend` and force push it.

**Comment by anencore94** [comment]
> @anencore94 Thanks for the contribution. Would this be a better solution?
> 
> ```shell
> kubectl version --short=true | awk 'FNR == 2 {print}'| awk -F '.' '{print $2}'
> ```
> 
> This would only use `awk`.
> 
> Also, please sign your commit by doing `git commit -s --amend` and force push it.

Sounds good. I've updated it. Thanks @andyi2it

**Review by andyi2it — APPROVED** [review]

**Pull request merged**
