### PR TITLE
Refractor v1 vs. v2 endpoint unit tests in kserve/test/test_server.py…

### LINKED ISSUE #3137: refactor v1 vs. v2 endpoint unit tests
Separate out v1 and v2 endpoint unit tests in https://github.com/kserve/kserve/blob/master/python/kserve/test/test_server.py.

### PR DESCRIPTION
**Pull request by guohaoyu110**
… and solve some python lint issues

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3137 

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by guohaoyu110** [comment]
@sivanantha321   The test still has this issue, do you know why?  https://github.com/kserve/kserve/issues/3146

**Comment by guohaoyu110** [comment]
@sivanantha321 Could you look at this error? Thank you for solving the timeout error https://github.com/kserve/kserve/issues/3146 But i really do not get this error for this test_inference_graph.py E2E Tests Error

**Comment by sivanantha321** [comment]
@guohaoyu110 It seems the [net-kourier pod is in crashBackLoop state](https://github.com/kserve/kserve/actions/runs/6366180000/job/17415908300?pr=3158#step:17:106). I am not sure what is causing this problem. I looked through the logs of net-kourier and i am not able to find any useful info except [this warning](https://github.com/kserve/kserve/actions/runs/6366180000/job/17415908300?pr=3158#step:17:3973). Can you try rerunning the tests?

**Comment by guohaoyu110** [comment]
> @guohaoyu110 It seems the [net-kourier pod is in crashBackLoop state](https://github.com/kserve/kserve/actions/runs/6366180000/job/17415908300?pr=3158#step:17:106). I am not sure what is causing this problem. I looked through the logs of net-kourier and i am not able to find any useful info except [this warning](https://github.com/kserve/kserve/actions/runs/6366180000/job/17415908300?pr=3158#step:17:3973). Can you try rerunning the tests?

I think i have no permission to rerun the tests.

**Comment by sivanantha321** [comment]
> I think i have no permission to rerun the tests.

You just have to force push to the branch :)

**Comment by guohaoyu110** [comment]
> > I think i have no permission to rerun the tests.
> 
> You just have to force push to the branch :)

Thank you. just done!

**Comment by yuzisun** [comment]
Thanks @guohaoyu110 !!

/lgtm
/approve

**Comment by guohaoyu110** [comment]
Hi, may i ask why this pr is not merged since it passes all the requirements?

**Pull request merged**
