### PR TITLE
Fix multi-arch docker publish

### PR DESCRIPTION
**Pull request by ddelange**
**What this PR does / why we need it**:

Docker images were not pushed to `kserve/<image>` anymore ref https://github.com/kserve/kserve/pull/2605#discussion_r1055816046

Artifact from #2549, #2550, #2604, #2605

**Type of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Fix multi-arch docker publish
```

### CODE REVIEW

**Comment by yuzisun** [comment]
Thanks @ddelange ! Let’s verify after merging this 

/lgtm
/approve

**Comment by yuzisun** [comment]
@ddelange the image build is way too slow now, it is taking an hour and used to be 3 minutes.

**Comment by ddelange** [comment]
@yuzisun yes, QEMU is painstakingly slow. you could shave off a decent amount of time by limiting builds to the 64bit architectures: amd64, arm64, ppc64le

but won't be what it was without emulation. would be interesting to compare build times with those of knative...

**Comment by ddelange** [comment]
ah s390x is IBM's 64bit arch. didn't know that. isn't IBM one of the initial contributors to this project?

**Comment by ddelange** [comment]
controller is [done](https://github.com/kserve/kserve/actions/runs/3765802519/jobs/6401680244) and [looks](https://hub.docker.com/r/kserve/kserve-controller/tags) good

**Pull request merged**
