### PR TITLE
Upgraded poetry version to 1.7.1

### PR DESCRIPTION
**Pull request by andyi2it**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
This will need a rebase if my PR ever gets merged first :-) https://github.com/kserve/kserve/pull/3309

**Comment by sivanantha321** [comment]
LGTM

**Comment by terrytangyuan** [comment]
LGTM

**Pull request merged**
