### PR TITLE
Make deployment scheduling behaviour configurable

### PR DESCRIPTION
**Pull request by ddelange**
**What this PR does / why we need it**:

Allow running on multi-arch clusters (or single arch clusters that are not amd64)

We'd like to add a mix of tolerations and nodeSelectors to force or prefer arm64 scheduling etc (different preferences for other users)

Multi-arch images are incoming:
- https://github.com/kserve/modelmesh/pull/76
- https://github.com/kserve/kserve/pull/2550

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ddelange** [comment]
three more PRs opened for multi-arch helm chart:
- https://github.com/kserve/kserve/pull/2628
- https://github.com/kserve/modelmesh/pull/76
- https://github.com/kserve/rest-proxy/pull/18

**Comment by yuzisun** [comment]
@ddelange Can you help resolve the merge conflict?

**Comment by ddelange** [comment]
@yuzisun done 🤙

**Comment by yuzisun** [comment]
Thanks @ddelange for the great contribution !!

/lgtm
/approve

**Pull request merged**
