### PR TITLE
Loosen setuptools lower pin

### PR DESCRIPTION
**Pull request by ddelange**
**What this PR does / why we need it**:

This PR fixes compatibility with `torch==1.10.*` (which implicitly depends on `setuptools<=59.5.0` ref https://github.com/awslabs/autogluon/pull/1786#issuecomment-1149288383) and so allows serving custom models trained using those torch versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Fix compatibility of the python package with torch==1.10.*
```

### CODE REVIEW

**Comment by ddelange** [comment]
cc @Suresh-Nakkeran as you raised the lower pin in #2103

**Comment by ddelange** [comment]
@yuzisun all green, do you think this PR can still be included in v0.9.0-rc0?

**Comment by ddelange** [comment]
@pvaneck taking the liberty to ping you ^^

**Review by pvaneck — COMMENTED** [review]
/lgtm
However, I am wondering if `setuptools` even needs to be specified in the `requirements.txt` file. Should be included with the Python distribution like `pip` is, right?

**Comment by ddelange** [comment]
not all distributions include it. conda does, pyenv does, homebrew does. but e.g. apt-get doesnt: making a venv from [here](https://github.com/ddelange/pycuda/blob/b8d5765/runtime/Dockerfile) will require the user to install setuptools [separately](https://github.com/ddelange/pycuda/blob/b8d5765/vanilla/Dockerfile#L13)

**Comment by ddelange** [comment]
@pvaneck anything from my side still?

**Pull request merged**
