### PR TITLE
Remove kubeflow copyright

### LINKED ISSUE #16: KServe License Update
/kind feature

**Describe the solution you'd like**
- Change [LICENSE](https://github.com/kserve/kserve/blob/master/hack/boilerplate.go.txt#L2) file line 2 to
`Copyright 2020 The KServe Authors`
- For new files created in kserve use `Copyright 2020 The KServe Authors`, for existing files remove the original `Copyright 2020 kubeflow.org`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #16 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by Tomcli** [comment]
/hold
Some issue on merging the status for this PR, hold it for now since it's using up the bot quota

**Comment by pvaneck** [comment]
/hold
Hah, prow server still complaining about this PR. Needs a force push.

**Pull request merged**
