### PR TITLE
fix a typo in OPENSHIFT_GUIDE.md

### LINKED ISSUE #3543: There is an invalid link in OPENSHIFT_GUIDE.md
/kind bug

**What steps did you take and what happened:**
The installation manual points to:
`oc apply -f "https://github.com/kserve/kserve/releases/download/${KSERVE_VERSION}/kserve-cluster-resoucess.yaml"`
and it's the invalid link.

The correct line should be (resoucess-> resources):
`oc apply -f "https://github.com/kserve/kserve/releases/download/${KSERVE_VERSION}/kserve-cluster-resources.yaml"`

**What did you expect to happen:**
The installation can be done directly following the described steps.

### PR DESCRIPTION
**Pull request by marek-veber**
**What this PR does / why we need it**:
This is a intuitive small typo fix.

**Which issue(s) this PR fixes**:
Fixes #3543

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

**Feature/Issue validation/testing**:
Test if  the fixed link points to valid page.

**Release note**:
```release-note
 * fix a typo in OPENSHIFT_GUIDE.md
```

### CODE REVIEW

**Comment by sivanantha321** [comment]
@marek-veber Thanks for the fix ! Can you help sign-off the commit to pass the DCO check ?

**Review by sivanantha321 — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
