### PR TITLE
Literal $ in URL for v2 inference protocol doc

### PR DESCRIPTION
**Pull request by luranhe**
**What this PR does / why we need it**:
Without escaping, Github Markdown treats 2 "$" characters in the same line as [equation delimiters](https://github.blog/2022-05-19-math-support-in-markdown/). Current file is not so readable:
image

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
N/A
```

### CODE REVIEW

**Comment by luranhe** [comment]
Fixed:
image

**Review by pvaneck — COMMENTED** [review]
Thanks! Much more readable now.
/lgtm

**Pull request merged**
