### PR TITLE
Fix snyk scan null error

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Snyk scan is still failing due to invalid value in the sarif file. This PR replaces the invalid null value with "0".
Screenshot from 2024-10-07 12-46-48

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Tested in my fork repo
Screenshot from 2024-10-07 12-47-43

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Review by spolti — APPROVED** [review]
/approve

**Review by terrytangyuan — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Review by yuzisun — APPROVED** [review]

**Comment by sivanantha321** [comment]
@terrytangyuan @yuzisun I think e2e tests are not triggered for workflow changes https://github.com/kserve/kserve/blob/6ff2a2f6be4852cdcd2625dba134e810a1c24d28/.github/workflows/e2e-test.yml#L6-L11

**Comment by terrytangyuan** [comment]
Would you like to make that change in this PR too?

**Comment by spolti** [comment]
can we have this merged?

**Review by yuzisun — APPROVED** [review]

**Pull request merged**
