### PR TITLE
add json mimetype header for IG response

### LINKED ISSUE #2401: Inference graph always returns response with Content-Type as "text/plain; charset=utf-8"
/kind bug

**What steps did you take and what happened:**
Created a an IG with a single ISVC as a node that is a custom predictor. This node returns JSON response body with Content-Type header as `application/json`.
Now when I call IG with this single node then IG returns response with Content-Type header as `text/plain; charset=utf-8`.

**What did you expect to happen:**
I expected Content-Type header of IG's response as `application/json`.
Ideally, IG's response should have all the characteristics of the last node's response in that IG.

**Anything else you would like to add:**
On investigating further I found that this is happening because of using ResponseWriter's `Write` method on line [L181](https://github.com/kserve/kserve/blob/master/cmd/router/main.go#L181) in router's code.
If you see [documentation of ResponseWriter's `Write`](https://go.dev/src/net/http/server.go#L120) method, the we see that , this method uses `DetectContentType` which uses https://mimesniff.spec.whatwg.org/ algorithm.
And this algorithm can't determine `application/json` and hence IG returns Content-Type as `text/plain; charset=utf-8`.
See this [issue](https://github.com/golang/go/issues/10630)

**Environment:**

- Istio Version: 1.13
- Knative Version: 1.4.0
- KServe Version: 0.9.0
- Kubeflow version: NA
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: NA
- Kubernetes version: (use `kubectl version`): v1.21.13-eks-84b4fe6
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by krazik-intuit**
**What this PR does / why we need it**:
correct mimetype response for graph router when json is used

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2401 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by rachitchauhan43** [comment]
@krazik-intuit : Can you fix the DCO check ?

**Comment by krazik-intuit** [comment]
@rachitchauhan43 done

**Comment by rachitchauhan43** [comment]
@yuzisun / @sukumargaonkar : LGTM for a short term fix, specifically for json responses. 
As main problem is that `mimesniff` is not able to detect json content-type so setting the Content-Type as `application/json` in case of valid json response body.

Long term fix will be to propagate last node's response's Content-Type as IG's response Content-Type to make sure all the content-types supported at ISVC level are supported at IG level too. 

WDYT ?

**Comment by krazik-intuit** [comment]
re: #2401

**Comment by yuzisun** [comment]
Thanks @krazik-intuit !

/lgtm
/approve

**Pull request merged**
