### PR TITLE
Fix kserve annotation constants

### PR DESCRIPTION
**Pull request by ddelange**
kserve was setting incorrect annotations for scale bounds ref https://knative.dev/docs/serving/autoscaling/scale-bounds/

**What this PR does / why we need it**:

Fix kserve annotation constants for scale bounds

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
@ddelange This isn’t a bug as Knative has changed the annotation name since 1.1 version and the old annotation name is still supported. But thanks for changing to the new name, looks like there are a few tests need to be fixed.

**Comment by ddelange** [comment]
@yuzisun by the way, when I set annotations on the resource at top level (e.g. this `max-scale`), they don't get propagated to the knative Service:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/max-scale: "4"
    autoscaling.knative.dev/metric: concurrency
    autoscaling.knative.dev/target: "4"
    autoscaling.knative.dev/target-burst-capacity: "8"
```

Is there a nested location where I could set these per-revision knative settings such that they propagate into the knative Service definition? I couldn't find `annotations` entry here: https://kserve.github.io/website/reference/api/#serving.kserve.io/v1beta1.PredictorSpec

On a knative Service it would look like:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
...
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/target: "3"
        autoscaling.knative.dev/target-burst-capacity: "6"
      creationTimestamp: null
    spec:
      containerConcurrency: 50
      containers:
      - args:
        ...
```

**Comment by yuzisun** [comment]
> @yuzisun by the way, when I set annotations on the resource at top level (e.g. this `max-scale`), they don't get propagated to the knative Service:
> 
> ```yaml
> apiVersion: serving.kserve.io/v1beta1
> kind: InferenceService
> metadata:
>   annotations:
>     autoscaling.knative.dev/max-scale: "4"
>     autoscaling.knative.dev/metric: concurrency
>     autoscaling.knative.dev/target: "4"
>     autoscaling.knative.dev/target-burst-capacity: "8"
> ```
> 
> Is there a nested location where I could set these per-revision knative settings such that they propagate into the knative Service definition? I couldn't find `annotations` entry here: https://kserve.github.io/website/reference/api/#serving.kserve.io/v1beta1.PredictorSpec
> 
> On a knative Service it would look like:
> 
> ```yaml
> apiVersion: serving.knative.dev/v1
> kind: Service
> ...
> spec:
>   template:
>     metadata:
>       annotations:
>         autoscaling.knative.dev/max-scale: "100"
>         autoscaling.knative.dev/metric: concurrency
>         autoscaling.knative.dev/min-scale: "0"
>         autoscaling.knative.dev/target: "3"
>         autoscaling.knative.dev/target-burst-capacity: "6"
>       creationTimestamp: null
>     spec:
>       containerConcurrency: 50
>       containers:
>       - args:
>         ...
> ```

KServe does not use the `min-scale` and `max-scale` annotation, it defines explicit `minReplicas` and `maxReplicas` fields. for metrics and target there are also corresponding fields defined on InferenceService.

**Comment by ddelange** [comment]
ok thanks :) anything else from my side here?

**Comment by yuzisun** [comment]
@ddelange Thanks for the fix!

/lgtm
/approve

**Pull request merged**
