### PR TITLE
[release-0.11] publish helm chart to ghcr

### PR DESCRIPTION
**Pull request by davidspek**
**What this PR does / why we need it**:
This PR is a cherry pick of https://github.com/kserve/kserve/pull/3319 which extends the CI to push the helm charts to GHCR so that users can easily install KServe using them. It is necessary to add this to the current release branch so new releases will have the chart pushed to GHCR.
Examples of the charts published from this PR can be seen here:
https://github.com/davidspek/kserve/pkgs/container/charts%2Fkserve
https://github.com/davidspek/kserve/pkgs/container/charts%2Fkserve-crd

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
ci: publish helm charts to GHCR
```

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Do we also want to publish these retroactively for previous releases?

**Comment by davidspek** [comment]
@terrytangyuan It might be nice, but I'm not sure how you'd want to do that with the current CI. If you have push permissions to the org you could check out the various release tags locally and then run the commands to generate the `*.tgz` packages and push them to GHCR.

**Comment by terrytangyuan** [comment]
Unfortunately I don't have permission to help with that.

**Comment by davidspek** [comment]
I could change the workflow so it can also be manually run by triggering it from the GitHub UI to at least backfill the last version of the chart. Do you have the permissions for that on this repo?

**Comment by terrytangyuan** [comment]
I would love to help but I don't have permission since I am not a maintainer of KServe. @yuzisun and others might be able to help further here.

**Comment by yuzisun** [comment]
We do not plan to publish for 0.11, let's aim for 0.12

**Pull request closed without merging**
