### PR TITLE
Fix triton + torchscript guidelines to be executable

### PR DESCRIPTION
**Pull request by Curt-Park**
Signed-off-by: Jinwoo Park (Curt) www.jwpark.co.kr@gmail.com

**What this PR does / why we need it**:

- ~Fixed some misleading hyperlinks~
- ~Fixed wrong key value (`image.json`)~
- ~Fixed curl commands~

-> These changes are contained in [another PR of KServe Website](https://github.com/kserve/website/pull/127).

- Deleted descriptions in `README.md` by @yuzisun's suggestion 

**Release note**:

```release-note
Fix Triton with TorchScript guidelines to be executable
```

### CODE REVIEW

**Comment by yuzisun** [comment]
@Curt-Park We actually have the exactly same tutorial on website,  what do you think just delete this and link to the website [here](https://github.com/kserve/website/tree/main/docs/modelserving/v1beta1/triton/torchscript)?

**Comment by Curt-Park** [comment]
> @Curt-Park We actually have the exactly same tutorial on website,  what do you think just delete this and link to the website [here](https://github.com/kserve/website/tree/main/docs/modelserving/v1beta1/triton/torchscript)?

Okay. I will link the website and create a PR on the website repository.

**Comment by Curt-Park** [comment]
@yuzisun I just added [a link](https://github.com/kserve/website/tree/main/docs/modelserving/v1beta1/triton/torchscript) you mentioned  in `README.md` and didn't change anything else. I think the better way to fix is gathering all of the information for this tutorial in the same place (such as KServe website). However, the related codes have deleted months ago (https://github.com/kserve/website/commit/57c544662b9761142f171f64d4de8557675a444b) by you. I assume that there is any reason for what you've done.

Please let me know if you have any idea for this.

**Comment by yuzisun** [comment]
> @yuzisun I just added [a link](https://github.com/kserve/website/tree/main/docs/modelserving/v1beta1/triton/torchscript) you mentioned in `README.md` and didn't change anything else. I think the better way to fix is gathering all of the information for this tutorial in the same place (such as KServe website). However, the related codes have deleted months ago ([kserve/website@57c5446](https://github.com/kserve/website/commit/57c544662b9761142f171f64d4de8557675a444b)) by you. I assume that there is any reason for what you've done.
> 
> Please let me know if you have any idea for this.

@Curt-Park yes the idea is to keep the doc in the `website` repo and code examples in the `kserve` repo because some of the examples are used by the e2e tests and it is also easier for contributor to create a PR for new feature with code examples.

**Comment by yuzisun** [comment]
thanks @Curt-Park !!

/lgtm
/approve

**Pull request merged**
