### PR TITLE
pass parameter  in rest v2 infer

### PR DESCRIPTION
**Pull request by Naegionn**
**What this PR does / why we need it**:
Fix InferInput Parameters not being passed in rest v2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # 
https://github.com/kserve/kserve/issues/2793
**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

I tested this change by editing the file in the installed lib. For testing I ran the Kserve Model Locally outside of a Cluster.

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by Naegionn** [comment]
This fix would change the behaviour such that if parameter is not set it will be set to None.

Another approach would be
```python
        infer_inputs = [InferInput(name=input.name, shape=input.shape, datatype=input.datatype,
                                   data=input.data,
                                   parameters={} if input.parameters is None else input.parameters
                                   ) for input in request_body.inputs]
```

Please advise on the prefered solution.

**Comment by yuzisun** [comment]
> This fix would change the behaviour such that if parameter is not set it will be set to None.
> 
> Another approach would be
> 
> ```python
>         infer_inputs = [InferInput(name=input.name, shape=input.shape, datatype=input.datatype,
>                                    data=input.data,
>                                    parameters={} if input.parameters is None else input.parameters
>                                    ) for input in request_body.inputs]
> ```
> 
> Please advise on the prefered solution.

Setting to None has a cost of extra check when getting the parameters, not sure if there is use case you want the value to be explicit None otherwise your suggestion would be preferable.

**Comment by Naegionn** [comment]
I updated my PR such that it will set parameters to {} if input.parameters is none.

**Comment by yuzisun** [comment]
Thanks @Naegionn !

/lgtm
/approve

**Pull request merged**
