### PR TITLE
Fix azure blob storage access key env not mounted

### LINKED ISSUE #4063: Azure blob storage access key env not mounted
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Previously issue #2392 was done to support shared access token as credentials for azure blob storage download. The feature utilizes`AZURE_STORAGE_ACCESS_KEY` for azure blob downloads in storage-initializer. However, `AZURE_STORAGE_ACCESS_KEY` env is not injected from controller for azure blob download when other secrets are injected as well (eg. `AZURE_CLIENT_ID`)

**What did you expect to happen:**
Able to access Azure Storage resources using shared access signatures

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by bentohset**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4063 
- adds optional `AZURE_STORAGE_ACCESS_KEY` to azure credential env mounting

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by bentohset** [comment]
inclusion of `AZURE_STORAGE_ACCESS_KEY` in azure secret shouldn't cause the credentials to be detected as azure storage access (file share) which would not mount `AZURE_CLIENT_ID` etc.

As long as condition of azure secret is before storage access key:
```golang
	} else if _, ok := secret.Data[azure.AzureClientId]; ok {
		log.Info("Setting secret envs for azure", "AzureSecret", secret.Name)
		envs := azure.BuildSecretEnvs(secret)
		container.Env = append(container.Env, envs...)
	} else if _, ok := secret.Data[azure.AzureStorageAccessKey]; ok {
		log.Info("Setting secret envs with azure storage access key for azure", "AzureSecret", secret.Name)
		envs := azure.BuildStorageAccessKeySecretEnv(secret)
		container.Env = append(container.Env, envs...)

```

**Comment by bentohset** [comment]
cc @lizzzcai

**Comment by lizzzcai** [comment]
/lgtm
Can you help to add example to the [doc](https://kserve.github.io/website/master/modelserving/storage/azure/azure/) as well.

**Pull request merged**
