### PR TITLE
Fixing indentation bug in image patch config

### LINKED ISSUE #2538: Wrong indentation in image_patch causing inference graph controller failure.
/kind bug

**What steps did you take and what happened:**
This `metricsAggregator` is improperly intended and hence it is getting inserted as part of router config and causing json marshalling errors in inference graph controller. 

Run make deploy-dev on master and check the value of inferenceservice-configmap:
`metricsAggregator` is getting appended into `router` section and when creating any IG, then IG controller fails to marshal router json from the config map.

**What did you expect to happen:**
`metricsAggregator` should be properly indented so that it doesn't get appended to `router` section

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by rachitchauhan43**
Signed-off-by: rachitchauhan43 <rachitchauhan43@gmail.com>

**What this PR does / why we need it**:
This `metricsAggregator` is improperly intended and hence it is getting inserted as part of router config and causing json marshalling errors in inference graph controller. 
I think this is where it got in https://github.com/kserve/kserve/pull/2478/files#r1025930852

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2538 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
@alexagriffith  to review

**Review by alexagriffith — APPROVED** [review]
Ah, sorry for some reason I didn't catch this- thank you

**Comment by yuzisun** [comment]
thanks @rachitchauhan43 !
/lgtm
/approve

**Pull request merged**
