### PR TITLE
Remove unwanted cluster scope secret permissions

### LINKED ISSUE #3724: ClusterRole permissions are too broadly scoped?
/kind question

Hello team,

I have a general question. I noticed that the permissions defined in the [kserve-manager-role](https://github.com/kserve/kserve/blob/v0.12.1/charts/kserve-resources/templates/clusterrole.yaml#L97-L108) for kserve-controller-manager are broadly scoped. For example:

````
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
````

This broad scope poses a security risk for us due to our compliance requirements. Is there a specific reason the role needs cluster-wide access to secrets? or can it be scoped down to certain namespaces? please advise

Thank you

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3724

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Remove unwanted cluster scope secret permissions
```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by spolti** [comment]
@israel-hdez please take a look

**Comment by terrytangyuan** [comment]
Fixes https://github.com/kserve/kserve/issues/3897

**Review by terrytangyuan — COMMENTED** [review]
Do we have any test that already covers this so that we know for sure it still works after the change?

**Comment by sivanantha321** [comment]
> Do we have any test that already covers this so that we know for sure it still works after the change?

I don't think we have e2e tests which uses secrets. I did some tests. So far nothing is broken. It would be nice if the community can test this change and provide some thoughts.

**Review by greenmoon55 — APPROVED** [review]
lgtm, I searched for "secrets" and I didn't find anything that might need these permissions.

**Review by yuzisun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
