### PR TITLE
bump to vllm0.6.3

### PR DESCRIPTION
**Pull request by hustxiayang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by yuzisun** [comment]
@sivanantha321 any thoughts on how we can create a GitHub action to publish vllm container image separately.

**Comment by sivanantha321** [comment]
> @sivanantha321 any thoughts on how we can create a GitHub action to publish vllm container image separately.

Sorry. I didn't understand the context. Can you explain a bit more ?

**Pull request merged**
