### PR TITLE
Enable Istio injection in e2e namespace and add Auth policy

### PR DESCRIPTION
**Pull request by DavidSpek**
**What this PR does / why we need it**:
This PR enabled Istio injection in the namespace created for KFServing during the E2E tests, and applies the Istio AuthorizationPolicy the profile-controller would deploy from PR https://github.com/kubeflow/kubeflow/pull/6013 to the testing namespace. The AuthorizationPolicy created by the profile-controller from PR https://github.com/kubeflow/kubeflow/pull/6013 differs slightly from the current one, as it adds the `/ready` and `/v1/models/*` paths to the allow array and adds a principal for this array ensuring only the KNative controller can access those paths. Without the selector, users could access those paths in any other user's namespace, breaking multi-user isolation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to https://github.com/kubeflow/kfserving/issues/1558

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yanniszark** [comment]
@DavidSpek thanks for the PR.
I think we should first agree on the AuthorizationPolicy that the profile-controller uses.
Right now, only part of that policy is merged in kubeflow/kubeflow.
Could you please:
- Update issue https://github.com/kubeflow/kubeflow/issues/5965 with the extra path you found, how you found out about it etc.
- Propose using the `/v1/models/*` in the AuthorizationPolicy as the immediate workaround. Another workaround would be to not inject InferenceService Pods. What are the pros/cons of each? (e.g., this authorizationpolicy affects unrelated pods).

Once we agree on those and merge https://github.com/kubeflow/kubeflow/pull/6013, then it should be ok to add this to KFServing. Or maybe we could even add an e2e test with a profile-controller created namespace, instead of copying the policy in two places?

**Comment by DavidSpek** [comment]
@yanniszark Thanks for your comments. I completely agree with all your points. I didn't intend for this PR to be merged as it is, for the obvious reason that the AuthorizationPolicy isn't what is currently created by the profile-controller. I was also thinking it would be possible to deploy the profile-controller as part of the E2E test, but I'm not sure if that conflicts with the reasoning behind the current setup. There are some more discrepancies I've found between the E2E tests and what would be deployed as part of Kubeflow and in a production environment.

I'll continue working on KFServing and KNative in the coming days and hopefully solve the current problems. Part of the reasoning behind this PR is to have a reference point to compare a deployment with Kubeflow to to figure out where things are going wrong.

**Comment by DavidSpek** [comment]
Kind ping @yanniszark With Istio injection enabled in the testing namespace and the AuthorizationPolicy the CI tests passed. I'm thinking this might be caused by the absence of a global deny-all rule. I'll test that next and tomorrow I'll look into the actual tests that are being run to see if that might be causing the discrepancy between my test environments and the E2E tests.

**Comment by DavidSpek** [comment]
@yanniszark @yuzisun
I think I found the problem why the E2E tests are passing although I wouldn't expect them to. Istio injection is being blocked by the IstioSpec that is being deployed:
https://github.com/kubeflow/kfserving/blob/774626b036bec7ecc24b539705d21408788f6a61/test/scripts/run-e2e-tests.sh#L53

This overrides the `istio-injection=enabled` label on namespaces (more information [here](https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/).
As such, Istio injection is not actually enabled in any of the namespaces.

**Comment by DavidSpek** [comment]
The E2E test has now failed since Istio injection actually enabled. I guess this is one of the rare situations where it is good news that the tests have failed.

I can't seem to easily copy all of the output logs, but I'll look at that more tomorrow. [Here](https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kfserving-presubmit-e2e-1688-eede877-4064-d385?tab=workflow&nodeId=kubeflow-kfserving-presubmit-e2e-1688-eede877-4064-d385-3718763960&sidePanel=logs%3Akubeflow-kfserving-presubmit-e2e-1688-eede877-4064-d385-3718763960%3Amain) is the link and the last section of the logs at least:

```
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED explainer/test_art_explainer.py::test_tabular_explainer - json.decoder...
FAILED batcher/test_batcher.py::test_batcher - json.decoder.JSONDecodeError: ...
FAILED explainer/test_aix_explainer.py::test_tabular_explainer - json.decoder...
FAILED predictor/test_lightgbm.py::test_lightgbm_kfserving - json.decoder.JSO...
FAILED logger/test_logger.py::test_kfserving_logger - json.decoder.JSONDecode...
FAILED explainer/test_tabular_explainer.py::test_tabular_explainer - json.dec...
FAILED predictor/test_multi_model_serving.py::test_mms_sklearn_kfserving[v2-storage_uris1]
FAILED predictor/test_multi_model_serving.py::test_mms_xgboost_kfserving[v2-storage_uris1]
FAILED predictor/test_sklearn.py::test_sklearn_kfserving - RuntimeError: Exce...
FAILED predictor/test_torchserve.py::test_torchserve_kfserving - RuntimeError...
FAILED predictor/test_triton.py::test_triton - RuntimeError: Exception when c...
FAILED predictor/test_xgboost.py::test_xgboost_kfserving - RuntimeError: Exce...
FAILED predictor/test_xgboost.py::test_xgboost_v2_kfserving - RuntimeError: E...
FAILED transformer/test_transformer.py::test_transformer - RuntimeError: Exce...
FAILED predictor/test_multi_model_serving.py::test_mms_xgboost_kfserving[v1-storage_uris0]
FAILED predictor/test_pytorch.py::test_pytorch - json.decoder.JSONDecodeError...
FAILED predictor/test_multi_model_serving.py::test_mms_sklearn_kfserving[v1-storage_uris0]
FAILED predictor/test_sklearn.py::test_sklearn_v2_kfserving - RuntimeError: E...
FAILED predictor/test_pmml.py::test_pmml_kfserving - json.decoder.JSONDecodeE...
FAILED predictor/test_tensorflow.py::test_tensorflow_kfserving - RuntimeError...
============ 20 failed, 1 passed, 8 warnings in 1026.47s (0:17:06) =============
```

**Comment by yuzisun** [comment]
> The E2E test has now failed since Istio injection actually enabled. I guess this is one of the rare situations where it is good news that the tests have failed.
> 
> I can't seem to easily copy all of the output logs, but I'll look at that more tomorrow. [Here](https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kfserving-presubmit-e2e-1688-eede877-4064-d385?tab=workflow&nodeId=kubeflow-kfserving-presubmit-e2e-1688-eede877-4064-d385-3718763960&sidePanel=logs%3Akubeflow-kfserving-presubmit-e2e-1688-eede877-4064-d385-3718763960%3Amain) is the link and the last section of the logs at least:
> 
> ```
> -- Docs: https://docs.pytest.org/en/stable/warnings.html
> =========================== short test summary info ============================
> FAILED explainer/test_art_explainer.py::test_tabular_explainer - json.decoder...
> FAILED batcher/test_batcher.py::test_batcher - json.decoder.JSONDecodeError: ...
> FAILED explainer/test_aix_explainer.py::test_tabular_explainer - json.decoder...
> FAILED predictor/test_lightgbm.py::test_lightgbm_kfserving - json.decoder.JSO...
> FAILED logger/test_logger.py::test_kfserving_logger - json.decoder.JSONDecode...
> FAILED explainer/test_tabular_explainer.py::test_tabular_explainer - json.dec...
> FAILED predictor/test_multi_model_serving.py::test_mms_sklearn_kfserving[v2-storage_uris1]
> FAILED predictor/test_multi_model_serving.py::test_mms_xgboost_kfserving[v2-storage_uris1]
> FAILED predictor/test_sklearn.py::test_sklearn_kfserving - RuntimeError: Exce...
> FAILED predictor/test_torchserve.py::test_torchserve_kfserving - RuntimeError...
> FAILED predictor/test_triton.py::test_triton - RuntimeError: Exception when c...
> FAILED predictor/test_xgboost.py::test_xgboost_kfserving - RuntimeError: Exce...
> FAILED predictor/test_xgboost.py::test_xgboost_v2_kfserving - RuntimeError: E...
> FAILED transformer/test_transformer.py::test_transformer - RuntimeError: Exce...
> FAILED predictor/test_multi_model_serving.py::test_mms_xgboost_kfserving[v1-storage_uris0]
> FAILED predictor/test_pytorch.py::test_pytorch - json.decoder.JSONDecodeError...
> FAILED predictor/test_multi_model_serving.py::test_mms_sklearn_kfserving[v1-storage_uris0]
> FAILED predictor/test_sklearn.py::test_sklearn_v2_kfserving - RuntimeError: E...
> FAILED predictor/test_pmml.py::test_pmml_kfserving - json.decoder.JSONDecodeE...
> FAILED predictor/test_tensorflow.py::test_tensorflow_kfserving - RuntimeError...
> ============ 20 failed, 1 passed, 8 warnings in 1026.47s (0:17:06) =============
> ```
> 
> What does slightly worry me is that the E2E tests don't seem to have been running correctly since #1334 was merged. So I hope the l there haven't been any PRs that were merged in the past 4 months that inadvertently broke things things.

@DavidSpek Where do you think e2e test is not running correctly? It is a good idea to enable the istio injection for e2e testing but I would suggest creating another ephemeral e2e kind cluster with istio proxy enabled and we do not have to run comprehensive test suite there.

**Comment by DavidSpek** [comment]
@yuzisun Istio is being installed, but sidecars aren't being injected anywhere, which is the source of problems and the most important thing to test. I am using a couple different clusters for testing this on already, but am using the E2E tests here so I can compare with my running clusters.

**Comment by yuzisun** [comment]
> @yuzisun Istio is being installed, but sidecars aren't being injected anywhere, which is the source of problems and the most important thing to test. I am using a couple different clusters for testing this on already, but am using the E2E tests here so I can compare with my running clusters.

@DavidSpek We purposely did not inject istio sidecar in e2e test as we do not want to make istio as a hard dependency for KFServing, I do not see any reason why KFServing does not work with istio proxy after setting up the right authorization policy, we could setup another dedicated e2e test env to test istio mesh cases.

**Comment by DavidSpek** [comment]
@yuzisun I was also wanting to ask if E2E tests with Istio should be a separate thing or not. However, given that the istio injection label was being applied to the knative-serving namespace explicitly, I assumed that sidecar injection was meant to be disabled.
I've outlined the reason it does not work even with the correct authorization policy [here](https://github.com/kubeflow/kfserving/issues/1371#issuecomment-869768880). [This](https://github.com/istio/istio/issues/23494) upstream Istio issue is also related.

**Comment by yuzisun** [comment]
closing this as we now have the guideline for the auth setup have https://kserve.github.io/website/0.10/admin/serverless/servicemesh/

**Pull request closed without merging**
