### PR TITLE
Publish helm chart as release asset

### LINKED ISSUE #2188: Add packaged helm chart to release assets
/kind feature

**Describe the solution you'd like**

It would be great to be able to deploy the helm chart (in my case using terraform) without having to clone this repo.

**Anything else you would like to add:**

Example Github Actions workflow to add the packaged helm chart to the release assets (which url can then be passed to helm similar to `kubectl -f`): https://github.com/ray-project/kuberay/pull/199/files

With the current folder structure going `cd manifests && helm package charts` would result in `charts-v0.8.0.tgz` and then this action would upload `helm-chart-charts-v0.8.0.tgz`. Might be worth adding one more level of nesting, i.e. `manifests/charts/kserve` and then going `cd manifests/charts && helm package kserve` resulting in `helm-chart-kserve-v0.8.0.tgz` under the release assets

### PR DESCRIPTION
**Pull request by ddelange**
**What this PR does / why we need it**:

Allow installing the helm chart without the user having to clone, nor kserve having to set up a helm repository.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2188 

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Workflow succeeded https://github.com/ddelange/kserve/runs/6525109187?check_suite_focus=true
- [x] Asset uploaded https://github.com/ddelange/kserve/releases/tag/v0.8.0-helm

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
The kserve helm chart has moved to `charts/kserve` and is now packaged and uploaded as a GitHub release asset for every (pre)release. Its URL can be directly passed to the `helm install` command.
```

### CODE REVIEW

**Comment by yuzisun** [comment]
@ddelange Thanks for the work with helm! My question is that currently crd is part of one helm chart, as far as I know when we upgrade the chart [helm does not update the crd ](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts)if anything is changed in this case. Should we create a separate chart for crd as helm recommended?

**Comment by ddelange** [comment]
Oh interesting, I didn't know! I'm guessing that can be a separate issue, this workflow will attempt to `helm package` any folder under the `charts/` path and uploads the archives as separate release assets.

**Comment by ddelange** [comment]
Indeed looks like istio also splits it up! https://istio.io/latest/docs/setup/install/helm/#installation-steps

**Comment by yuzisun** [comment]
> Indeed looks like istio also splits it up! https://istio.io/latest/docs/setup/install/helm/#installation-steps

yes let's split the crd out then.

**Comment by ddelange** [comment]
I can give it a shot. Should it be a separate PR? If yes, should it be merged before this one?

**Comment by yuzisun** [comment]
> I can give it a shot. Should it be a separate PR? If yes, should it be merged before this one?

Yes we can merge this one first, thanks!

**Comment by ddelange** [comment]
@yuzisun I rebased my commit on latest master, in the hope that the flakey (?) [test](https://github.com/kserve/kserve/runs/6633058337?check_suite_focus=true) will pass this time 🤞

**Comment by ddelange** [comment]
@yuzisun could you trigger CI for this PR?

**Comment by yuzisun** [comment]
> @yuzisun could you trigger CI for this PR?

@ddelange done, can you help rebase and resolve the conflict ?

**Comment by ddelange** [comment]
@yuzisun pushed, there was no conflict according to `git` :)

**Comment by yuzisun** [comment]
Thanks @ddelange! will test out this with the 0.9.0-rc0 release.

/lgtm
/approve

**Pull request merged**
