### PR TITLE
fix: Add missing volume mount to transformer container when using modelcars

### PR DESCRIPTION
**Pull request by rhuss**
Adding the missing mount of the emptyDir volume that holds the symbolic link to the model data in the model sidecar to a transformer container, if it is configured.

**What this PR does / why we need it**:

This PR fixes a bug when using transformer with modelcars in the serving runtime

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

No issue yet (since the fix is obvious), happy to open one if needed.

**Type of changes**
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

**Feature/Issue validation/testing**:

See the included unit test, that also tests that the proper volume mount is added
when no transformer is used

**Checklist**:

- [X] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [X] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
This is a fix, right? If so, could you update the PR title to start with "fix: "?

**Comment by rhuss** [comment]
Not sure why this test is failing, this PR doesn't touch anything in this area.

@terrytangyuan @yuzisun would it be possible to merge this fix before the next release ? It actually fixes a severe issue when running transformers with modelcar.

**Comment by terrytangyuan** [comment]
yes we should 

/assign @yuzisun

**Pull request merged**
