### PR TITLE
chore: Free up disk space on E2E test GHA runner node

### LINKED ISSUE #2950: Need larger github action node to run triton test
/kind bug

**What steps did you take and what happened:**
Triton images are too big to fit into the current size of github action node, and currently the test is disable because of that.
https://github.com/kserve/kserve/blob/master/test/e2e/predictor/test_triton.py#L31

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by ckadner**
### Motivation

Some end-to-end tests cannot be run using GitHub Actions due to limited disk space.  

We can free up disk space by following some best practices to [reduce disk usage for GitHub action runners](https://github.com/marketplace/actions/maximize-build-disk-space) by [deleting binaries that are not needed](https://github.com/actions/runner-images/issues/2840#issuecomment-790492173).

```
sudo rm -rf /usr/share/dotnet
sudo rm -rf /opt/ghc
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
```

### Modifications

```YAML
      - name: Free up disk space
        run: |
          # remove non-essential tools and libraries
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/boost

          # delete libraries for Android (12G), CodeQL (5.3G), PowerShell (1.3G), Swift (1.7G)
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "${AGENT_TOOLSDIRECTORY}/CodeQL"
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/swift
```

### Result

Increased available disk space by **21 GB** (plus **1 GB** after pruning docker images).

- **Before** cleanup:

  https://github.com/kserve/kserve/actions/runs/5183670232/jobs/9342128918#step:5:44

  Filesystem | Size | **Used** | **Avail** | Use%  | Mounted on
  ---------- | ---- | ---- | ----- | ----- | ----------
  /dev/root  |  84G |  **57G** |   **27G** |  **68%**  | /
  ...      | ... | ... |  ... | ...  | ...

- **After** cleanup:

  https://github.com/kserve/kserve/actions/runs/5183670232/jobs/9342128918#step:5:54

  Filesystem | Size | **Used** | **Avail** | Use%  | Mounted on
  ---------- | ---- | ---- | ----- | ----- | ----------
  /dev/root  |  84G |  **36G** |   **48G** |  **44%**  | /
  ...      | ... | ... |  ... | ...  | ...

- After **pruning** docker images:

  https://github.com/kserve/kserve/actions/runs/5183670232/jobs/9342128918#step:5:1218

  ```
  Total reclaimed space: 3.606GB
  
  TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
  Images          21        21        1.643GB   106.5MB (6%)
  Containers      40        40        162B      0B (0%)
  Local Volumes   0         0         0B        0B
  Build Cache     0         0         0B        0B
  ```
  ```
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/root        84G   35G   49G  43% /
  ```

Resolves #2950

### CODE REVIEW

**Comment by ckadner** [comment]
@yuzisun -- this PR is ready for review now. Its sole focus is on providing more storage on the GitHub Action runners for E2E tests. I added the disk clean-up step into the Minikube setup action, assuming where ever Minikube is being used, more disk space is need. 

I tried to re-enable the Triton (and other skipped) tests, but I assume more setup is needed for those which is best tackled in a separate PR by someone more familiar with the test setup.

**Comment by yuzisun** [comment]
@ckadner I fixed a merge conflict, can you check if I did correctly?

**Comment by ckadner** [comment]
> @ckadner I fixed a merge conflict, can you check if I did correctly?

Looks good @yuzisun -- Thanks!

**Comment by yuzisun** [comment]
Thanks @ckadner for fixing the disk spaces!

/lgtm
/approve

**Pull request merged**
