### PR TITLE
Add ARM64 arch support for serving runtimes

### LINKED ISSUE #2989: Unable to fetch image "docker.io/kserve/sklearnserver:v0.10.0" in Minikube/Kind version: v1.30.1 on Darwin 13.4 (arm64)
/kind bug

**What steps did you take and what happened:**
I am facing issue in running inference service on my minikube for Kserve.

Screenshot 2023-06-13 at 6 06 26 AM

When trying to create my first inference service - https://kserve.github.io/website/0.10/get_started/first_isvc/#run-your-first-inferenceservice

I am getting below error

docker.io/kserve/sklearnserver:v0.10.0 image is available on my minikube list of images (I have loaded it)
Screenshot 2023-06-13 at 6 08 11 AM

Please find the describe logs:
kubectl describe inferenceservices sklearn-iris -n kserve
Name: sklearn-iris
Namespace: kserve
Labels:
Annotations:
API Version: serving.kserve.io/v1beta1
Kind: InferenceService
Metadata:
Creation Timestamp: 2023-06-13T00:20:30Z
Finalizers:
inferenceservice.finalizers
Generation: 1
Resource Version: 742007
UID: 14692e0f-cce0-42fa-a743-fab3fc3cb830
Spec:
Predictor:
Model:
Model Format:
Name: sklearn
Name:
Resources:
Storage Uri: gs://kfserving-examples/models/sklearn/1.0/model
Status:
Components:
Predictor:
Latest Created Revision: sklearn-iris-predictor-default-00001
Conditions:
Last Transition Time: 2023-06-13T00:20:40Z
Message: Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "docker.io/kserve/sklearnserver:v0.10.0": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded.
Reason: RevisionFailed
Severity: Info
Status: False
Type: PredictorConfigurationReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Status: False
Type: PredictorReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Severity: Info
Status: False
Type: PredictorRouteReady
Last Transition Time: 2023-06-13T00:20:40Z
Message: Configuration "sklearn-iris-predictor-default" does not have any ready Revision.
Reason: RevisionMissing
Status: False
Type: Ready
Model Status:
States:
Active Model State:
Target Model State: Pending
Transition Status: InProgress
Observed Generation: 1
Events:
Type Reason Age From Message

Warning InternalError 4m18s v1beta1Controllers fails to reconcile predictor: fails to update knative service: Operation cannot be fulfilled on services.serving.knative.dev "sklearn-iris-predictor-default": the object has been modified; please apply your changes to the latest version and try again

Any help would be appreciated.

**What did you expect to happen:** The inference service takes the pre loaded image from minikube and starts the serving

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.17.2
- Knative Version: 
- KServe Version: 1.10.0
- Kubeflow version: 
- Cloud Environment: local
- Minikube/Kind version: v1.30.1 on Darwin 13.4 (arm64)
- Kubernetes version: (use `kubectl version`): v1.27.2
- OS (e.g. from `/etc/os-release`): Darwin 13.4 (arm64)

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2989

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Added ARM64 arch support for serving runtimes
```

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks, the update looks straightforward to me. FWIW, I stumbled upon the same issue when cross-compiling (however, I "just" installed  `gcc` which seemed good enough to compile the native parts in the dependencies, but I think the solution here is cleaner and more comprehensive even when it might add a bit more to the build times).

I wonder whether it would make sense to combine this with #3042 (if this makes sense to add), so that only one version bump would be required?

**Review by ckadner — APPROVED** [review]
Thank you @sivanantha321 -- this is very helpful! The changes look good, but there is a lot of duplicated code in the workflow YAML files and the Dockerfiles. 

For the GitHub actions/workflows, maybe we could [Reusable Workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) or [Composite Actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) to wrap the boilerplate and just provide the Dockerfile and image name as parameters/inputs.

https://stackoverflow.com/a/71570847/5601796

Similarly, for the Dockerfiles, maybe create a(nother) common base image that contains all the common layers?

But since this PR is good as it is, those changes could go into a separate PR later. WDYT?

**Comment by sivanantha321** [comment]
Thanks for the suggestion @ckadner. I agree with you. It would be nice to remove the duplicates. Let's handle it in a separate PR.

**Comment by sivanantha321** [comment]
@rhuss Thanks for the suggestion. But I think it is better to keep it as a different PR since, both are two different features.

**Review by ckadner — APPROVED** [review]
/lgtm

Need to resolve merge conflicts still, though.

**Comment by sivanantha321** [comment]
@yuzisun  @ckadner Currently, Paddle does not have [support for ARM64](https://github.com/deepjavalibrary/djl/issues/2083#issuecomment-1309157578).

**Comment by ckadner** [comment]
> @yuzisun @ckadner Currently, Paddle does not have [support for ARM64](https://github.com/deepjavalibrary/djl/issues/2083#issuecomment-1309157578).

I think that's okay. We could keep track of that in a separate issue.

**Review by ckadner — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
