### PR TITLE
Fix qpext metrics port

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:

When using qpext for scraping queue proxy metrics without turning on the metrics aggregation, it uses the wrong queue proxy metrics port 9090 which is for autoscaler metrics not the user metrics.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
    autoscaling.knative.dev/min-scale: "1"
    autoscaling.knative.dev/target: "5"
    autoscaling.knative.dev/targetBurstCapacity: "0"
    container.seccomp.security.alpha.kubernetes.io/queue-proxy: runtime/default
    identities.bloomberg.com/initContainerNames: storage-initializer
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"    <---- this is incorrect
    prometheus.io/scrape: "true"
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
    serving.knative.dev/creator: system:serviceaccount:kserve:kserve-controller-manager
    serving.kserve.io/enable-metric-aggregation: "false"
    serving.kserve.io/enable-prometheus-scraping: "true"
    sidecar.istio.io/inject: "false"
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Review by houshengbo — APPROVED** [review]

**Review by tessapham — APPROVED** [review]

**Review by alexagriffith — APPROVED** [review]

**Comment by alexagriffith** [comment]
> **What this PR does / why we need it**:
> 
> When using qpext for scraping queue proxy metrics without turning on the metrics aggregation, it uses the wrong queue proxy metrics port 9090 which is for autoscaler metrics not the user metrics.
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   annotations:
>     autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
>     autoscaling.knative.dev/min-scale: "1"
>     autoscaling.knative.dev/target: "5"
>     autoscaling.knative.dev/targetBurstCapacity: "0"
>     container.seccomp.security.alpha.kubernetes.io/queue-proxy: runtime/default
>     identities.bloomberg.com/initContainerNames: storage-initializer
>     prometheus.io/path: /metrics
>     prometheus.io/port: "9090"    <---- this is incorrect
>     prometheus.io/scrape: "true"
>     prometheus.kserve.io/path: /metrics
>     prometheus.kserve.io/port: "8080"
>     serving.knative.dev/creator: system:serviceaccount:kserve:kserve-controller-manager
>     serving.kserve.io/enable-metric-aggregation: "false"
>     serving.kserve.io/enable-prometheus-scraping: "true"
>     sidecar.istio.io/inject: "false"
> ```
> 
> **Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_: Fixes #
> 
> **Type of changes** Please delete options that are not relevant.
> 
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> **Feature/Issue validation/testing**:
> 
> Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced. Please also list any relevant details for your test configuration.
> 
> * [ ]  Test A
> * [ ]  Test B
> * Logs
> 
> **Special notes for your reviewer**:
> 
> 1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
> 
> **Checklist**:
> 
> * [ ]  Have you added unit/e2e tests that prove your fix is effective or that this feature works?
> * [ ]  Has code been commented, particularly in hard-to-understand areas?
> * [ ]  Have you made corresponding changes to the documentation?
> 
> **Release note**:
> 
> ```
> 
> ```

this should only happen when metrics-aggregation annotation is false but enable prometheus scraping metrics is true

**Pull request merged**
