### PR TITLE
Change the default value for enableDirectPvcVolumeMount to true

### PR DESCRIPTION
**Pull request by Jooho**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #https://github.com/kserve/kserve/issues/3370

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by sivanantha321** [comment]
We need to update the chart too. https://github.com/kserve/kserve/blob/c52753519e1802e73581856b1ae3a0f2f178d457/charts/kserve-resources/templates/configmap.yaml#L531

**Comment by Jooho** [comment]
@sivanantha321 updated

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/cc @sivanantha321

**Review by sivanantha321 — APPROVED** [review]

**Comment by Jooho** [comment]
@terrytangyuan @sivanantha321 can we include this pr to 0.12 as well?

**Pull request merged**
