### PR TITLE
Fix model download path

### LINKED ISSUE #3899: MLflow model cannot be served if storageUri doesn't end in "/"
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I set the `storageUri` (without `/`) as per the official documentation and tried to deploy the mlflow model, but it failed.
The error log is as follows:

```
2024-07-10 05:23:14,432 [mlserver.parallel] ERROR - An error occurred processing a model update of type 'Load'.
Traceback (most recent call last):
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 158, in _process_model_update
    await self._model_registry.load(model_settings)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/registry.py", line 299, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/registry.py", line 150, in load
    await self._load_model(new_model)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/registry.py", line 167, in _load_model
    model.ready = await model.load()
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver_mlflow/runtime.py", line 158, in load
    self._model = mlflow.pyfunc.load_model(model_uri)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlflow/tracing/provider.py", line 237, in wrapper
    is_func_called, result = True, f(*args, **kwargs)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 1017, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path, model_config)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 718, in _load_pyfunc
    return _PyTorchWrapper(_load_model(path, device=device), device=device)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlflow/pytorch/__init__.py", line 612, in _load_model
    pytorch_model = torch.load(model_path, **kwargs)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models/data/model.pth'

```
When I add `/` to the end of the `storageUri` set in the `InferenceService yaml`,  the inferenceService is able to start normally.  

Example:

`InferenceService yaml`
```
storageUri: "s3://<uri>/model/"
```
However, this doesn't match what the official documentation says.

The official documentation: https://kserve.github.io/website/master/modelserving/v1beta1/mlflow/v2/#deploy-with-inferenceservice

**What did you expect to happen:**

I expected to be able to download the model files in the correct path without adding `/` to the end of the storageUri.

If this is not possible, I request that the official documentation be modified to inform users that they need to add `/` after the storageUri to get it to work properly.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "<name>"
  namespace: "<namespace>"
  labels:
    <labels>
spec:
  predictor:
    serviceAccountName: <serviceAccountName>
    runtimeClassName: <runtimeClassName>
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://<uri>/model"
      resources:
        limits:
          nvidia.com/gpu: 1
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I used `kubectl exec -it <podname> -c kserve-container -n <namespace>`  to get inside the container and viewed the contents of the downloaded model files.

I noticed that the path of the model file download did not match the path I had saved on MLflow.

Path to the model file saved in mlflow: `<uri>/model/data/model.pth`

```
model
|-data
| |-model.pth
|-<other files>
```

Path to the model file I actually found in the container: `/mnt/models/model.pth`

```
bash-5.1$ ls /mnt/models
data  *model.pth  <other files>
bash-5.1$ ls /mnt/models/data
<other files>
exit
```

When I add `/` to the end of the `storageUri` set in the `InferenceService yaml`, the path to the model file in the container becomes:

```
bash-5.1$ ls /mnt/models/
data  <other files>
bash-5.1$ ls /mnt/models/data
model.pth  <other files>
```

I think the key is in this code below.

https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage/storage.py#L226-L259

Changing this code above to the following might solve the problem.

Sample code:
```
diff --git a/python/kserve/kserve/storage/storage.py b/python/kserve/kserve/storage/storage.py
index fb9b8d30..8d2e1c02 100644
--- a/python/kserve/kserve/storage/storage.py
+++ b/python/kserve/kserve/storage/storage.py
@@ -233,36 +233,8 @@ class Storage(object):
             # Skip where boto3 lists the directory as an object
             if obj.key.endswith("/"):
                 continue
-            # In the case where bucket_path points to a single object, set the target key to bucket_path
-            # Otherwise, remove the bucket_path prefix, strip any extra slashes, then prepend the target_dir
-            # Example:
-            # s3://test-bucket
-            # Objects: /a/b/c/model.bin /a/model.bin /model.bin
-            #
-            # If 'uri' is set to "s3://test-bucket", then the downloader will
-            # download all the objects listed above, re-creating their subpaths
-            # under the temp_dir.
-            # If 'uri' is set to "s3://test-bucket/a", then the downloader will
-            # add to temp_dir: b/c/model.bin and model.bin.
-            # If 'uri' is set to "s3://test-bucket/a/b/c/model.bin", then
-            # the downloader will add to temp dir: model.bin
-            # (without any subpaths).
-            # If the bucket path is s3://test/models
-            # Objects: churn, churn-pickle, churn-pickle-logs
-            bucket_path_last_part = bucket_path.split("/")[-1]
-            object_last_path = obj.key.split("/")[-1]
-
-            if bucket_path == obj.key:
-                target_key = obj.key.rsplit("/", 1)[-1]
-                exact_obj_found = True
-            elif bucket_path_last_part and object_last_path.startswith(
-                bucket_path_last_part
-            ):
-                target_key = object_last_path
-            else:
-                target_key = obj.key.replace(bucket_path, "").lstrip("/")
-
-            target = f"{temp_dir}/{target_key}"
+            target_key = os.path.relpath(obj.key, bucket_path)
+            target = os.path.join(temp_dir, target_key)
             if not os.path.exists(os.path.dirname(target)):
                 os.makedirs(os.path.dirname(target), exist_ok=True)
             bucket.download_file(obj.key, target)
```

**Environment:**

- Istio Version: v1.21.0
- Knative Version: v1.13.1
- KServe Version: v0.12.0
- Kubeflow version:
- Cloud Environment: k8s_istio
- Minikube/Kind version:
- Kubernetes version: v1.29.3

### PR DESCRIPTION
**Pull request by hakuro95**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3899

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by greenmoon55** [comment]
Could you add a test case for this?

**Comment by lizzzcai** [comment]
Maybe @andyi2it can help to take a look. There were couple of issues and PRs on the download path in the past.

**Comment by hakuro95** [comment]
> 您能为此添加一个测试用例吗？

I've tested it in my local environment, but I have a few questions about the test cases.
Does "adding test cases" refer to adding test code to a KServe directory (e.g., under test/e2e)?
If so, should I add the test code to test/e2e, such as in test/e2e/predictor/test_mlflow.py, or create a new directory under test/e2e?
Alternatively, would smoke tests or unit tests suffice? 
Creating the test cases will take some time. I will update you upon completion.

**Comment by hakuro95** [comment]
@greenmoon55 
> Could you add a test case for this?

I've tested it in my local environment, but I have a few questions about the test cases.
Does "adding test cases" refer to adding test code to a KServe directory (e.g., under test/e2e)?
If so, should I add the test code to test/e2e, such as in test/e2e/predictor/test_mlflow.py, or create a new directory under test/e2e?
Alternatively, would smoke tests or unit tests suffice? 
Creating the test cases will take some time. I will update you upon completion.

**Comment by hakuro95** [comment]
I can't fix the signature problem, so I'm going to close this request and create a new one once I've correctly branched the code.

**Pull request closed without merging**
