### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:

Update owners file based on the recent poll for the reviewer and committer promotion. 

Screenshot 2024-09-30 at 12 56 30 AM

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM. Congratulations everyone!

**Comment by terrytangyuan** [comment]
Reposting what @yuzisun shared on Slack:


We’re excited to announce the next round of contributor promotions and extend our thanks for all the valuable contributions you’ve made to KServe!  Based on our statistics, we have identified several candidates eligible for promotion to reviewers or committers. For your reference, we’ve attached the statistics for PR contributions and comments/reviews. Please note that these nominations take into account a variety of factors, including code quality, review contributions, community involvement, advocacy, design work, documentation, and overall adoption.

```
Contributors to 'kserve/kserve' (PR commenters, reviewers) by number of PRs (>5) since 2023-09-08:

334  yuzisun            [3921, 3917, 3911, 3910, 3907, 3898, 3893, 3890, 3886, 3885, ... ]
131  terrytangyuan      [3912, 3910, 3907, 3893, 3888, 3885, 3878, 3877, 3871, 3867, ... ]
 79  spolti             [3912, 3910, 3893, 3888, 3885, 3878, 3877, 3863, 3861, 3850, ... ]
 60  sivanantha321      [3918, 3902, 3878, 3877, 3867, 3808, 3802, 3787, 3775, 3761, ... ]
 24  lizzzcai           [3885, 3871, 3819, 3810, 3779, 3737, 3735, 3729, 3666, 3635, ... ]
 20  israel-hdez        [3758, 3746, 3735, 3721, 3672, 3653, 3615, 3484, 3476, 3469, ... ]
 12  rachitchauhan43    [3504, 3469, 3407, 3405, 3367, 3291, 3213, 3199, 3194, 3188, ... ]
 11  johnugeorge        [3871, 3743, 3723, 3715, 3700, 3680, 3676, 3582, 3530, 3459, ... ]
  9  Jooho              [3921, 3885, 3842, 3711, 3603, 3298, 3294, 3259, 3216]
  8  gavrissh           [3849, 3824, 3788, 3783, 3771, 3558, 3518, 3334]
  8  cmaddalozzo        [3716, 3677, 3657, 3626, 3590, 3589, 3571, 3334]
  8  ckadner            [3476, 3417, 3392, 3250, 3237, 3236, 3157, 3141]
  6  Datta0             [3910, 3802, 3788, 3771, 3723, 3712]
  5  greenmoon55        [3893, 3885, 3828, 3773, 3160]
  5  houshengbo         [3898, 3678, 3633, 3209, 3134]
  5  danielezonca       [3486, 3472, 3444, 3436, 3345]

Contributors to 'kserve/kserve' (PR authors) by number of PRs (>5) since 2023-09-08:

 85  sivanantha321      [3917, 3893, 3890, 3874, 3850, 3849, 3834, 3828, 3822, 3813, ... ]
 39  terrytangyuan      [3650, 3642, 3641, 3620, 3619, 3604, 3603, 3579, 3578, 3576, ... ]
 29  andyi2it           [3881, 3786, 3779, 3653, 3607, 3585, 3552, 3551, 3550, 3511, ... ]
 18  spolti             [3765, 3761, 3633, 3598, 3596, 3569, 3556, 3548, 3520, 3488, ... ]
 17  yuzisun            [3867, 3866, 3810, 3719, 3718, 3680, 3679, 3616, 3530, 3524, ... ]
 10  Jooho              [3878, 3877, 3808, 3476, 3463, 3392, 3371, 3267, 3250, 3172]
 10  gavrissh           [3821, 3802, 3688, 3684, 3676, 3589, 3464, 3459, 3415, 3217]
 10  israel-hdez        [3737, 3711, 3472, 3435, 3434, 3324, 3316, 3245, 3244, 3242]
 10  cmaddalozzo        [3673, 3666, 3665, 3659, 3654, 3622, 3621, 3614, 3582, 3568]
  5  houshengbo         [3773, 3705, 3615, 3529, 3210]
  5  grandbora          [3716, 3694, 3658, 3590, 3581]
```

**Comment by spolti** [comment]
Congratz everyone!

**Pull request merged**
