### PR TITLE
fix image-transformer built image tag

### PR DESCRIPTION
**Pull request by theofpa**
**What this PR does / why we need it**:
the build of the `image-transformer` publishes in the ecr of `kfserving:latest`, and it's overlapping with the `kfserving` project

### CODE REVIEW

**Comment by theofpa** [comment]
created the following repositories in the ecr registry of the `optional-test-infra` aws account:
```
$ aws ecr describe-repositories |grep repositoryName|grep kserve
            "repositoryName": "kserve/kfserving-controller",
            "repositoryName": "kserve/image-transformer",
            "repositoryName": "kserve/storage-initializer",
            "repositoryName": "kserve/aix-explainer",
            "repositoryName": "kserve/batcher",
            "repositoryName": "kserve/alibi-explainer",
            "repositoryName": "kserve/xgbserver",
            "repositoryName": "kserve/pmmlserver",
            "repositoryName": "kserve/art-explainer",
            "repositoryName": "kserve/pytorchserver",
            "repositoryName": "kserve/sklearnserver",
            "repositoryName": "kserve/agent",
            "repositoryName": "kserve/lgbserver",
            "repositoryName": "kserve/logger",
```

and with f7e92a7 we're moving the push and the pull of the images to these new repos.

**Comment by pugangxa** [comment]
Generally it's good, but @yuzisun not sure whether we plan some other places planed for kserve dedicately?

**Comment by yuzisun** [comment]
> Generally it's good, but @yuzisun not sure whether we plan some other places planed for kserve dedicately?

this is for testing images, for release images we are using the kserve dockerhub org, but maybe at some point we should consider migrating also, for now it is good.

**Comment by yuzisun** [comment]
thanks @theofpa !

/lgtm
/approve

**Pull request merged**
