### PR TITLE
feat: CA bundle mount options for storage initializer

### LINKED ISSUE #2897: Custom certificate bundle for storage initializer
/kind feature

**Describe the solution you'd like**

The current version of KServe provides the `serving.kserve.io/s3-cabundle` annotation that allows administrators to specify the path to a certificate bundle for HTTPS validations during S3 resource initialization. However, I'm wondering if there is a way to mount a certificate bundle in the storage initializer container without having to rebuild the image.

Can KServe mount volume from secret into the container it generates? This would allow administrators to easily mount the necessary certificate bundle without the need to rebuild the container image.

**Anything else you would like to add:**

Example based on [Knative](https://knative.dev/docs/serving/tag-resolution/#procedure):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
        - name: controller
          volumeMounts:
            - name: custom-certs
              mountPath: /path/to/custom/certs
          env:
            - name: SSL_CERT_DIR
              value: /path/to/custom/certs
      volumes:
        - name: custom-certs
          secret:
            secretName: custom-certs
```

### PR DESCRIPTION
**Pull request by ckadner**
This PR is a collaboration between @jooho and @danilopeixoto based on the work done by @danilopeixoto in PR #2906 and some additional fixes contributed by @Jooho

It addresses #2897

Related issues listed in #3171

---

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2897

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Test injected CA bundle secret volume
- [x] Test not injected CA bundle secret volume

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
CA bundle mount options for storage initializer
```

### CODE REVIEW

**Comment by ckadner** [comment]
@Jooho -- are you able to push to this branch?

**Comment by Jooho** [comment]
@ckadner fyi go build failed with existing pr. I am not sure if i can push source to this branch or not yet

**Comment by Jooho** [comment]
@ckadner nvm, I found a typo in the test file. I will fix it.

**Comment by Jooho** [comment]
@ckadner I don't have permission to push commit into this branch.

**Comment by ckadner** [comment]
> @ckadner I don't have permission to push commit into this branch.

@Jooho you may have to create a PR onto this branch.

**Comment by ckadner** [comment]
The collaboration branch idea did not pan out. @Jooho just created a new PR #3250 with all of @danilopeixoto commits to establish co-authorship

https://github.com/kserve/kserve/pull/3250

**Pull request closed without merging**
