### PR TITLE
fix: orphan cluster role kserve-addressable-resolver

### LINKED ISSUE #3929: Orphan cluster role kserve-addressable-resolver deployed
/kind bug

**What steps did you take and what happened:**
We have noticed three instances of an orphan resource in some of your Kubernetes configuration files. Deploying Kubernetes resources that are not being actively used or referenced by any other resources in the cluster can lead to orphan resources. These orphan resources consume unnecessary resources and can potentially cause confusion or clutter within the cluster. Additionally, we provide anecdotal evidence from [topolvm-topolvm#484](https://github.com/topolvm/topolvm/issues/484) regarding the orphan resource defect.

cluster role kserve-addressable-resolver does not have a role binding:

https://github.com/kserve/kserve/blob/29731befb0a1721d42e642f09f5ec62f1eafd522/charts/kserve-resources/templates/clusterrole.yaml#L320C9-L320C36

**What did you expect to happen:**
cluster role kserve-addressable-resolver should have a role binding, otherwise it is a orphan resource. Or delete kserve-addressable-resolver to avoid deploy orphan resource.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by zhangyue110026**
**What this PR does / why we need it**: fixes orphan cluster role

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3929 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Why not adding a rolebinding if that's what's missing?

**Comment by zhangyue110026** [comment]
@terrytangyuan Deleting orphan resources just one possible fix, I propose this fix as I am not sure this cluster role should bind to which sa. If you think this fix is improper, please propose a proper fix. 😄

**Comment by yuzisun** [comment]
> @terrytangyuan Deleting orphan resources just one possible fix, I propose this fix as I am not sure this cluster role should bind to which sa. If you think this fix is improper, please propose a proper fix. 😄

The addressable role is used along side with Knative, the role binding is defined in knative as it is selecting these external roles by label `duck.knative.dev/addressable`.

https://github.com/knative/serving/blob/edb073ce7c2d158d2e46ea3610d1b72c5f002d92/config/core/200-serviceaccount.yaml#L68

https://github.com/knative/serving/blob/edb073ce7c2d158d2e46ea3610d1b72c5f002d92/config/core/200-roles/addressable-resolvers-clusterrole.yaml#L25

**Comment by yuzisun** [comment]
My suggestion is to introduce a helm variable to add/remove this role

**Comment by zhangyue110026** [comment]
@yuzisun You are right. Could you please propose new commits?

**Comment by yuzisun** [comment]
This is taken care here with a flag https://github.com/kserve/kserve/blob/master/charts/kserve-resources/templates/addressable_resolver_role.yaml

**Pull request closed without merging**
