### PR TITLE
Rename KF prefixed classes

### LINKED ISSUE #1947: Renaming: KFServer KFModelRepository KFModel ?
Currently in the Python SDK there are still some names relating to the old KFServing name:

`KFServer`
`KFModelRepository`
`KFModel`

Should these be renamed?

If so my suggestion is to remove the prefixes entirely as they're already part of the `KServe` package already.

So just `Server` `ModelRepository` `Model` would be sufficient I think.

Updating the names would also require:
- Updating the python model servers e.g. lgbserver, sklearnserver etc.
- Updating the documentation examples

### PR DESCRIPTION
**Pull request by markwinter**
**What this PR does / why we need it**:

1. Renames the following:
  - `KFModel` -> `Model`
  - `KFServer` -> `ModelServer`
  - `KFModelRepository` -> `ModelRepository`
  - `kserve.api.kf_serving_client` -> `kserve.api.kserve_client`
  - `kserve.api.kf_serving_watch` -> `kserve.api.watch`

Also updated some comments that said KFServing still

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1947

**Release note**:

```release-note
KF-prefixed components have been renamed
  - `KFModel` -> `Model`
  - `KFServer` -> `ModelServer`
  - `KFModelRepository` -> `ModelRepository`
  - `kserve.api.kf_serving_client` -> `kserve.api.kserve_client`
  - `kserve.api.kf_serving_watch` -> `.kserve.api.watch`
```

### CODE REVIEW

**Comment by markwinter** [comment]
This is just the first step. All renaming is contained in the first commit.

There will be additional commits to update the Python model servers

**Comment by markwinter** [comment]
@yuzisun 
It seems the alibiexplainer tests don't use the updated kserve code.
All the other tests seem to be fine with finding the new class names.
Any idea why?

```
==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_anchor_images.py _________________
alibiexplainer/tests/test_anchor_images.py:14: in <module>
    from alibiexplainer.anchor_images import AnchorImages
alibiexplainer/alibiexplainer/__init__.py:14: in <module>
    from .explainer import AlibiExplainer  # noqa # pylint: disable=unused-import
alibiexplainer/alibiexplainer/explainer.py:38: in <module>
    class AlibiExplainer(kserve.Model):
E   AttributeError: module 'kserve' has no attribute 'Model'
------------------------------- Captured stderr --------------------------------
2021-12-17 07:24:19.089691: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
2021-12-17 07:24:19.089742: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
________________ ERROR collecting tests/test_anchor_tabular.py _________________
alibiexplainer/tests/test_anchor_tabular.py:18: in <module>
    from sklearnserver.model import SKLearnModel
sklearnserver/sklearnserver/__init__.py:14: in <module>
    from .model import SKLearnModel  # noqa # pylint: disable=unused-import
sklearnserver/sklearnserver/model.py:24: in <module>
    class SKLearnModel(kserve.Model):  # pylint:disable=c-extension-no-member
E   AttributeError: module 'kserve' has no attribute 'Model'
__________________ ERROR collecting tests/test_anchor_text.py __________________
alibiexplainer/tests/test_anchor_text.py:16: in <module>
    from .utils import Predictor
alibiexplainer/tests/utils.py:19: in <module>
    class Predictor:  # pylint:disable=too-few-public-methods
alibiexplainer/tests/utils.py:20: in Predictor
    def __init__(self, clf: kserve.Model):
E   AttributeError: module 'kserve' has no attribute 'Model'
____________________ ERROR collecting tests/test_parser.py _____________________
alibiexplainer/tests/test_parser.py:14: in <module>
    from alibiexplainer.parser import parse_args
alibiexplainer/alibiexplainer/__init__.py:14: in <module>
    from .explainer import AlibiExplainer  # noqa # pylint: disable=unused-import
alibiexplainer/alibiexplainer/explainer.py:38: in <module>
    class AlibiExplainer(kserve.Model):
E   AttributeError: module 'kserve' has no attribute 'Model'
```

**Comment by markwinter** [comment]
The alibiexplainer test seems to be uninstalling the kserve installed at the start of test and reinstalling kserve-0.7 wheel.

```
2021-12-19T13:00:55.7481129Z INFO: pip is looking at multiple versions of kserve to determine which version is compatible with other requirements. This could take a while.
2021-12-19T13:00:55.7723611Z Collecting kserve>=0.7.0
2021-12-19T13:00:55.7905093Z   Downloading kserve-0.7.0-py3-none-any.whl (284 kB)
...
2021-12-19T13:01:45.2908327Z   Attempting uninstall: kserve
2021-12-19T13:01:45.2918722Z     Found existing installation: kserve 0.7.0
2021-12-19T13:01:45.2928675Z     Uninstalling kserve-0.7.0:
2021-12-19T13:01:45.6305306Z       Successfully uninstalled kserve-0.7.0
2021-12-19T13:01:45.9215154Z   Running setup.py develop for alibiexplainer
```

**Comment by markwinter** [comment]
Between the alibiexplainer tests, `h5py==2.9.0` is installed, but this is incompatible with the tensorflow version requested by alibiexplainer's `setup.py`

```
  pip install -e ./alibiexplainer
  pip install h5py==2.9.0
  pytest ./alibiexplainer
```

```
2021-12-19T13:01:49.1730489Z Collecting h5py==2.9.0
2021-12-19T13:01:49.2322062Z   Downloading h5py-2.9.0-cp37-cp37m-manylinux1_x86_64.whl (2.8 MB)
2021-12-19T13:01:49.2983026Z Requirement already satisfied: six in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from h5py==2.9.0) (1.16.0)
2021-12-19T13:01:49.2994548Z Requirement already satisfied: numpy>=1.7 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from h5py==2.9.0) (1.18.5)
2021-12-19T13:01:50.5717584Z Installing collected packages: h5py
2021-12-19T13:01:50.5718232Z   Attempting uninstall: h5py
2021-12-19T13:01:50.5723530Z     Found existing installation: h5py 2.10.0
2021-12-19T13:01:50.5917251Z     Uninstalling h5py-2.10.0:
2021-12-19T13:01:50.5931764Z       Successfully uninstalled h5py-2.10.0
2021-12-19T13:01:50.7918823Z ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
2021-12-19T13:01:50.7920067Z Successfully installed h5py-2.9.0
2021-12-19T13:01:50.7921342Z tensorflow 2.3.2 requires h5py<2.11.0,>=2.10.0, but you have h5py 2.9.0 which is incompatible.
```

**Comment by markwinter** [comment]
Looks like this might be the cause

```
tritonclient 2.14.2 requires numpy>=1.19.1, but you have numpy 1.18.5 which is incompatible.
xgbserver 0.7.0 requires xgboost==0.82, but you have xgboost 1.0.2 which is incompatible.
lgbserver 0.7.0 requires numpy==1.19.5, but you have numpy 1.18.5 which is incompatible.
```

**Comment by markwinter** [comment]
This is ready to be reviewed now.

Need to update all documentation and examples after this

**Comment by yuzisun** [comment]
@markwinter Can you help rebase from master to pick up the [e2e tests fix](https://github.com/kserve/kserve/pull/1959) ?

**Comment by markwinter** [comment]
@yuzisun Done

**Comment by yuzisun** [comment]
Thanks @markwinter! 

/lgtm
/approve

**Pull request merged**
