### PR TITLE
Updating Knative Serving and Istio to their latest version

### PR DESCRIPTION
**Pull request by matzew**
**What this PR does / why we need it**:

Updating the Knative bits to the 1.9.0 release, which is the latest release, and Istio to 1.16.2, which is also the latest stable release.

Needed to have the quick start components on a recent version, from upstream community

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
(not actually a bug, more polishing)

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Tested by running the quickstart against `KinD` locally, after the changes

**Special notes for your reviewer**:

Updating to latest of Knative Serving and Istio

**Checklist**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
@matzew Thanks for the PR! 

Have you tested this? I think there are some breaking changes in Knative 1.8 for the domain configurations.
https://kserve.github.io/website/0.10/admin/serverless/serverless/#1-install-knative-serving

**Comment by rachitchauhan43** [comment]
> @matzew Thanks for the PR!
> 
> Have you tested this? I think there are some breaking changes in Knative 1.8 for the domain configurations. https://kserve.github.io/website/0.10/admin/serverless/serverless/#1-install-knative-serving


Even next iteration of istio from 1.16 to 1.17 is also breaking. See here https://github.com/knative/serving/issues/13712 
@matzew : Can you please explain how you tested this ?

**Comment by yuzisun** [comment]
> > @matzew Thanks for the PR!
> > Have you tested this? I think there are some breaking changes in Knative 1.8 for the domain configurations. https://kserve.github.io/website/0.10/admin/serverless/serverless/#1-install-knative-serving
> 
> Even next iteration of istio from 1.16 to 1.17 is also breaking. See here [knative/serving#13712](https://github.com/knative/serving/issues/13712) @matzew : Can you please explain how you tested this ?

I made a commit to patch the domain to expose the service on ingress as this is for demo testing purpose and user would want to call the service externally.

**Comment by skonto** [comment]
@yuzisun @matzew I am actively working on improving OCP docs. A lot has changed since the time this was documented.

**Comment by rachitchauhan43** [comment]
@yuzisun / @matzew : When we update say knative's version in `quick_install.sh` script, do we also update where KNative's binaries in places like https://github.com/kserve/kserve/blob/master/qpext/go.mod#L11 ?
cc: @ckadner

**Pull request merged**
