### PR TITLE
Fix failed build for knativeLocalGatewayService

### PR DESCRIPTION
**Pull request by yuzisun**
**What this PR does / why we need it**:

Error: vet: pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go:791:5: unknown field IngressServiceName in struct literal of type "github.com/kserve/kserve/pkg/apis/serving/v1beta1".IngressConfig
make: *** [Makefile:181: vet] Error 1
Error: Process completed with exit code 2.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
I wonder why this wasn't caught by the CI

**Comment by yuzisun** [comment]
> I wonder why this wasn't caught by the CI

Not sure how did this happen, likely the code is merged from master without conflicts but the CI did not rerun.

**Comment by yuzisun** [comment]
> > I wonder why this wasn't caught by the CI
> 
> Not sure how did this happen, likely the code is merged from master without conflicts but the CI did not rerun.

related to the tests added in https://github.com/kserve/kserve/pull/3773 which is not compatible with https://github.com/kserve/kserve/commit/2fae6e214193adae5b82dc02899bdc2c6ff5b5e1

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
