### PR TITLE
bump to vllm 0.6.0

### PR DESCRIPTION
**Pull request by hustxiayang**
support vLLM 0.6.0

- [x] New feature (non-breaking change which adds functionality)

https://blog.vllm.ai/2024/09/05/perf-update.html

### CODE REVIEW

**Comment by hustxiayang** [comment]
@terrytangyuan  Hi,  I separated this two commits.  And sorry to trouble you, how to test it online? Thanks!

**Comment by lizzzcai** [comment]
Hi @hustxiayang , thanks for the PR. You can follow this [PR](https://github.com/kserve/kserve/pull/3911) to bump the version.

you need to run poetry as well to update the dependencies. finally you probably need to build the hggingface server and give it a test. (build the image mostly need GPU)

**Comment by yuzisun** [comment]
@hustxiayang Can you clean up the commits as it includes someone else's PR commits

**Comment by yuzisun** [comment]
> Hi @hustxiayang , thanks for the PR. You can follow this [PR](https://github.com/kserve/kserve/pull/3911) to bump the version.
> 
> you need to run poetry as well to update the dependencies. finally you probably need to build the hggingface server and give it a test. (build the image mostly need GPU)

I think we can merge the PR as we do have test coverage unless there is something unexpected on GPU, but we are going to verify right away internally on GPU after it is merged.

**Review by yuzisun — APPROVED** [review]

**Pull request merged**
