### PR TITLE
Update AIF explainer example 

### LINKED ISSUE #1886: Update AIF explainer example with the latest knative API.
/kind bug

**What steps did you take and what happened:**
Since KServe is updated with a later version of knative. Knative service v1alpha1 is not longer supported, so we need to update the AIF example to use the latest knative API.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Tomcli**
**What this PR does / why we need it**:
Update the AIF explainer example with the correct commands and fix the message dumper knative version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1886

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzisun** [comment]
@Tomcli Can you help update [website repo](https://github.com/kserve/website/tree/main/docs/modelserving/detect/aif/germancredit) as well? We are aiming to move over all the docs to website.

**Comment by Tomcli** [comment]
thanks @yuzisun I will also add a PR to the website

**Comment by Tomcli** [comment]
Here is the one for website https://github.com/kserve/website/pull/52/files

**Pull request merged**
