### PR TITLE
Use kubectl -k instead of kustomize

### LINKED ISSUE #2633: Flaky minikube setup github action
/kind bug

**What steps did you take and what happened:**
```
Run ./test/scripts/gh-actions/setup-deps.sh
  ./test/scripts/gh-actions/setup-deps.sh
  
  kubectl get pods -n istio-system
  kubectl describe svc -n istio-system istio-ingressgateway
  kubectl get pods -n knative-serving
  kubectl get pods -n cert-manager
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    GOROOT: /opt/hostedtoolcache/go/1.17.3/x64
    MINIKUBE_HOME: /home/runner/work/_temp
Installing/Updating kustomize ...
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
```

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by yuzisun**
Signed-off-by: Dan Sun <dsun20@bloomberg.net>

**What this PR does / why we need it**:
Use `kubectl apply -k` instead of installing kustomize as it always gets rate limit error when all github actions are triggered.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2633 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Special notes for your reviewer**:

1. Also need to pin fastapi to 0.88 as 0.89 requires response type be pandatic models.
**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by tenzen-y** [comment]
We may need to change in other places too.

For example, we need to replace one with `kubectl` in the following:
https://github.com/kserve/kserve/blob/60dc5faf2c3c0b28edc3dc1911deb6868b895c15/Makefile#L116-L120

Since we run `make deploy-ci` in the following:
https://github.com/kserve/kserve/blob/d3f254453827388908d67abc897943d9ee01b878/test/scripts/gh-actions/setup-kserve.sh#L24

**Comment by yuzisun** [comment]
@tenzen-y the test passed, can you approve ?

**Review by tenzen-y — COMMENTED** [review]
@yuzisun Thanks!
/lgtm

**Review by tenzen-y — APPROVED** [review]

**Comment by tenzen-y** [comment]
@kserve-oss-bot ping

**Comment by tenzen-y** [comment]
Prow might be crashed?

**Comment by yuzisun** [comment]
> Prow might be crashed?

```
We couldn’t deliver this payload: x509: certificate has expired or is not yet valid: current time 2023-01-08T14:56:57Z is after 2023-01-07T05:26:41Z
```
The prow certificate expired, @ckadner can this be renewed still but I know we need to find a new home.

**Comment by yuzisun** [comment]
> > Prow might be crashed?
> 
> ```
> We couldn’t deliver this payload: x509: certificate has expired or is not yet valid: current time 2023-01-08T14:56:57Z is after 2023-01-07T05:26:41Z
> ```
> 
> The prow certificate expired, @ckadner can this be renewed still ? I know we need to find a new home.

**Comment by yuzisun** [comment]
We need to prioritize https://github.com/kserve/kserve/issues/2535. I am merging this manually for now as it is blocking other PRs.

**Pull request merged**
