### PR TITLE
chore: Update list of reviewers

### PR DESCRIPTION
**Pull request by ckadner**
### Semi-annual cleanup of PR reviewers

Updating the list of `reviewers` in the project [OWNERS](https://github.com/kserve/kserve/blob/master/OWNERS#L5-L18) file to better reflect who is actively helping with PR reviews.

#### Add new reviewers:

Project contributors who have reviewed more than 10 PRs in the past 180 days who are not currently listed as official `reviewers`:

```
  - israel-hdez
  - terrytangyuan
```

#### Remove inactive reviewers:

Current `reviewers` who have not reviewed or commented on any PRs in the past 180 days:

```
  - adriangonz
  - iamlovingit
  - sukumargaonkar
  - theofpa
  - njhill
```

---

<details><summary><b>PR review activity during past 180 days</b></summary>

Using the [kserve/community: scripts/python/list-contributors.py](https://github.com/kserve/community/blob/main/scripts/python/list-contributors.py) script we can find all active PR reviewers in the past 180 days with reviewed PRs in brackets.

```
[kserve/community]$ ./scripts/python/list-contributors.py -r reviewer commenter -n 1 -d 180 | sort -k1.6 -f | grep -v "kserve/kserve"

  1  ajstewart          [3368]
  1  alexagriffith      [3209]
  1  AlexFly666         [3334]
  4  andyi2it           [3431, 3394, 3244, 3213]
  1  chauhang           [3217]
  8  ckadner            [3476, 3417, 3392, 3250, 3237, 3236, 3157, 3141]
  1  cmaddalozzo        [3334]
  4  danielezonca       [3472, 3444, 3436, 3345]
  1  davidspek          [3325]
  1  ddelange           [3285]
  1  DnPlas             [3188]
  1  dtrifiro           [3267]
  1  gavrishp           [3334]
  1  gawsoftpl          [3319]
  1  greenmoon55        [3160]
  2  houshengbo         [3209, 3134]
 10  israel-hdez        [3436, 3364, 3354, 3318, 3306, 3285, 3267, 3266, 3259, 3202]
  2  johnugeorge        [3459, 3334]
  4  Jooho              [3298, 3294, 3259, 3216]
  3  lizzzcai           [3463, 3303, 3213]
  1  luksa              [3316]
  1  nguyenthai0107     [3172]
 10  rachitchauhan43    [3407, 3405, 3367, 3291, 3213, 3199, 3194, 3188, 3178, 3167]
  1  rhuss              [3339]
 22  sivanantha321      [3447, 3435, 3429, 3410, 3395, 3394, 3374, 3371, 3364, 3340, ... ]
  4  spolti             [3472, 3444, 3417, 3389]
  1  taneem-ibrahim     [3110]
 53  terrytangyuan      [3481, 3480, 3476, 3472, 3469, 3464, 3463, 3460, 3459, 3458, ... ]
  2  tessapham          [3209, 3138]
  1  timothyjlaurent    [3273]
  1  Xaenalt            [3223]
152  yuzisun            [3480, 3475, 3466, 3464, 3463, 3458, 3450, 3449, 3444, 3442, ... ]
  1  zoramt             [3334]
  1  zregvart           [3110]

```
</details>

---

@yuzisun @rachitchauhan43

### CODE REVIEW

**Comment by ckadner** [comment]
@terrytangyuan @israel-hdez -- thank you for doing such an outstanding job of reviewing PRs!

**Review by israel-hdez — APPROVED** [review]
Thank you very much for the promotion!
I'll keep contributing to the project.

**Review by terrytangyuan — COMMENTED** [review]
Thank you!

**Comment by yuzisun** [comment]
Thanks @terrytangyuan and @israel-hdez for all the contributions !

/lgtm
/approve

**Comment by taneem-ibrahim** [comment]
Congratulations @terrytangyuan and @israel-hdez . Thank you for your outstanding contributions to the KServe community.

**Comment by spolti** [comment]
Congratulations @terrytangyuan and @israel-hdez

**Pull request merged**
