### PR TITLE
Fix explainer endpoint not working with path based routing

### LINKED ISSUE #3231: Explainer is not working with path based routing
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Followed the [Alibi explainer example in the website](https://kserve.github.io/website/0.11/modelserving/explainer/alibi/income/) with path based routing enabled.

Getting following error
```bash
 curl -v -H "Host: example.com" -H "Content-Type: application/json" -H "Knative-Serving-Tag: latest" http://localhost:8080/serving/default/income/v1/models/income:explain -d '{"instances":[[39, 7, 1, 1, 1, 1, 4, 1, 2174, 0, 40, 9]]}'
* Uses proxy env variable NO_PROXY == 'localhost,127.0.0.1'
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /serving/default/income/v1/models/income:explain HTTP/1.1
> Host: example.com
> User-Agent: curl/7.85.0
> Accept: */*
> Content-Type: application/json
> Knative-Serving-Tag: latest
> Content-Length: 57
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 501 Not Implemented
< content-length: 42
< content-type: application/json
< date: Wed, 08 Nov 2023 09:31:59 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 12
< 
* Connection #0 to host localhost left intact
{"error":"Could not find explainer_host."}
```
Ingress config
```json
{
    "ingressGateway" : "knative-serving/knative-ingress-gateway",
    "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
    "localGateway" : "knative-serving/knative-local-gateway",
    "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
    "ingressDomain"  : "example.com",
    "ingressClassName" : "istio",
    "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
    "urlScheme": "http",
    "disableIstioVirtualHost": false,
    "pathTemplate": "/serving/{{ .Namespace }}/{{ .Name }}"
}
```
**What did you expect to happen:**
Explainer should work with path based routing enabled

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.11.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sivanantha321**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3231
Depends on #3258

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Fix explainer endpoint not working when path based routing enabled
```

### CODE REVIEW

**Comment by sivanantha321** [comment]
We are waiting for the istio versions below 1.19.0 is no longer supported as this feature requires istio version 1.19,0 or higher.

**Comment by sivanantha321** [comment]
> We are waiting for the istio versions below 1.19.0 is no longer supported as this feature requires istio version 1.19,0 or higher.

[Istio 1.19 and below versions are no longer supported](https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases). We can update the minimum required Istio version for Kserve to 1.19.0 and merge this PR.

**Review by yuzisun — APPROVED** [review]

**Pull request merged**
