### PR TITLE
CWE-362 - anyio Race Condition

### PR DESCRIPTION
**Pull request by spolti**
chore:	Fixes CWE-362 - anyio Race Condition.
	Affected versions of this package are vulnerable to Race Condition in
	_eventloop.get_asynclib() that cause crashes when multiple event loops
	of the same backend are running in separate threads and simultaneously
	attempting to use AnyIO for the first time.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by spolti** [comment]
```
Building h5py requires pkg-config unless the HDF5 path is explicitly specified using the environment variable HDF5_DIR. For more information and details, see https://docs.h5py.org/en/stable/build.html#custom-installation
```

It is fixed as part of https://github.com/kserve/kserve/pull/3598/files#diff-a4f8129d1b3802e812533311dccd5fed46eb3d88c6a899c90fe9bcf431399ac6R19

**Review by terrytangyuan — DISMISSED** [review]
/lgtm

**Comment by spolti** [comment]
` You have reached your pull rate limit. You may increase the limit by authenticating and upgrading:`
I'll try again tomorrow.

**Comment by spolti** [comment]
Closing, if the alert is still valid, will send a PR later.

**Pull request closed without merging**
