### PR TITLE
Fix issue with rolling update behavior

### LINKED ISSUE #3768: RollingUpdate strategy is not effective for RawDeployment mode
/kind bug

**What steps did you take and what happened:**
When updating the inferenceService, deployment's replicas are not set, the deployment replicas will initially be set to 1, and then the HPA (Horizontal Pod Autoscaler) will adjust the replicas to the minReplicas value.

For example, in the case below, where minReplicas is set to 4, even under the default update strategy(maxUnavailable: 25%), it would simultaneously delete 3 pods, rather than just one.
```
sklearn-iris-predictor   4/4     4            4           3d19h
sklearn-iris-predictor   4/1     4            4           3d19h
sklearn-iris-predictor   4/1     0            4           3d19h
sklearn-iris-predictor   4/1     0            4           3d19h
sklearn-iris-predictor   1/1     0            1           3d19h
sklearn-iris-predictor   1/1     1            1           3d19h
sklearn-iris-predictor   1/4     1            1           3d19h
sklearn-iris-predictor   1/4     1            1           3d19h
sklearn-iris-predictor   1/4     1            1           3d19h
sklearn-iris-predictor   1/4     1            1           3d19h
sklearn-iris-predictor   1/4     3            1           3d19h
sklearn-iris-predictor   2/4     3            2           3d19h
sklearn-iris-predictor   3/4     3            3           3d19h
sklearn-iris-predictor   3/4     3            3           3d19h
sklearn-iris-predictor   3/4     3            3           3d19h
sklearn-iris-predictor   3/4     3            3           3d19h
sklearn-iris-predictor   3/4     4            3           3d19h
sklearn-iris-predictor   4/4     4            4           3d19h
sklearn-iris-predictor   4/4     4            4           3d19h
sklearn-iris-predictor   3/4     4            3           3d19h
sklearn-iris-predictor   4/4     4            4           3d19h
```

**What did you expect to happen:**
When creating a deployment, set replicas=minReplicas.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: default
spec:
  predictor:
    minReplicas: 4
    model:
      modelFormat:
        name: sklearn
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
RawDeployment
- Istio Version:
- Knative Version:
- KServe Version: v0.13.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by andyi2it**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3768 

**Type of changes**
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by yuzisun** [comment]
@andyi2it Can you help add a test for this?

**Comment by beratturan** [comment]
Hi, could you please review this PR? I'm encountering the same error, but thanks to this PR, I've managed to resolve the issue. It would be great if it could be merged into the master branch. @cmaddalozzo @rachitchauhan43 @israel-hdez

**Review by yuzisun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
