### PR TITLE
KServe 0.14 Release

### LINKED ISSUE #3872: Release 0.14 Tracking
# KServe 0.14.0 release tracking:

RC0 release Date: Will be released in the week of `August 26, 2024`
Release Date: Will be released in the week of `Sep 23, 2024`

## **TIMELINE**
| Week | Start                     | End                         | When | Event (Actual timelines)                                                                                |
| ---- |---------------------------| --------------------------- | ---- | ------------------------------------------------------------------------------------------------------- |
| 0-10  | **Week of  June 3, 2024**    | **August 23, 2024**       |      | **Feature Freeze + RC0 Released + Documentation update starts**                                             |
| 11-13   | **Week of August 26, 2024**       | **Sep 20, 2024**      |      | Testing   + End of documentation                                                                                               |
| 14   | **Sep 23 2024**  | **Sep 27, 2024**      |      | **Final release - 0.14.0 released**

### PR DESCRIPTION
**Pull request by greenmoon55**
**What this PR does / why we need it**: 
Following the release guide.
Cutoff commit https://github.com/kserve/kserve/tree/d2695a5888c88736f8f5ebfa5067d5f67f15f4c5

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3872 

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [ ] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

**Release note**:

```release-note

```

**Re-running failed tests**

- `/rerun-all` - rerun all failed workflows.
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Nice to have: https://github.com/kserve/kserve/pull/3759


I believe @israel-hdez is working on some final changes today and @yuzisun is reviewing.

**Comment by spolti** [comment]
Hi all, do you think we can make these two PRs for this release?

- https://github.com/kserve/kserve/pull/3902
- https://github.com/kserve/kserve/pull/3672

**Comment by yuzisun** [comment]
> Hi all, do you think we can make these two PRs for this release?
> 
> * [storage initializer segregation #3902](https://github.com/kserve/kserve/pull/3902)
> * [introduce service configuration at configmap level #3672](https://github.com/kserve/kserve/pull/3672)

We want to minimize the change as this is official release, we can follow up with 0.14.1?

**Pull request merged**
